### ISSUE TITLE
Split BERTModel class into BERTForClassification BERTForRegression

### ISSUE THREAD

**Issue by jzf2101** [mosaicml/composer#1018]
## 🚀 Feature Request
HF has some logic under the hood that looks at the number of labels in order to decide if whether to use a BCE, CE, or MSE loss.  

Splitting up the BERT class based on the loss and making these distinctions as to what loss is used to the user may be more clear.  It also aligns with the work of @Landanjs 

Note: this may also require creating a separate `.loss` method in the wrapper to get over this logic under the hood

See also discussion in #993  

@moinnadeem

**Comment by heytanay** [comment]
Hi, this seems interesting, can I work on this?

**Comment by nik-mosaic** [comment]
Hey, @heytanay , this class has been refactored and no longer exists. If you'd like to contribute, please reach out to @bandish-shah and he can point you to current issues.

**Comment by mvpatel2000** [comment]
As a side, we'll be cleaning up github issues soon! Sorry for the confusion.... We'd love help on other things though :)

**Comment by heytanay** [comment]
Thanks, @nik-mosaic and @mvpatel2000. Definitely looking forward to contributing to Mosaic. Should I wait for a few weeks till the issues are cleared?
