### ISSUE TITLE
Algorithms Need Access to Loss Function

### ISSUE THREAD

**Issue by jzf2101** [mosaicml/composer#1025]
## 🚀 Feature Request
Per discussion with @A-Jacobson, not all models based off `ComposerModel` provide a callable.  Examples include [`GPT2Model`](https://github.com/mosaicml/composer/blob/61f07c946e1703d01a84065d10ee055367279811/composer/models/gpt2/model.py#L76-L80) and [`BertModel`](https://github.com/mosaicml/composer/blob/61f07c946e1703d01a84065d10ee055367279811/composer/models/bert/model.py#L86-L90).  Algorithms such as [`selective_backprop` need access to the loss as a callable](https://github.com/mosaicml/composer/blob/61f07c946e1703d01a84065d10ee055367279811/composer/algorithms/selective_backprop/selective_backprop.py#L215).  See also #993 for transformer specific discussion.

**Comment by mvpatel2000** [comment]
Closing, we won't impose this on all models
