### ISSUE TITLE
ERROR: File "setup.py" or "setup.cfg" not found.

### ISSUE THREAD

**Issue by abdulsam** [mosaicml/composer#1091]
I'm using **colab**
I run the following code in colab cell:
```
!git clone https://github.com/mosaicml/composer.git

!cd composer

!pip install -e ".[all]"

```
I followed the instructions mentioned on [installation](https://docs.mosaicml.com/en/stable/getting_started/installation.html) page.

![Screenshot 2022-05-26 114955](https://user-images.githubusercontent.com/11463868/170429240-e29a8a09-4f57-4f83-9ffe-b1b5f2e4d395.png)

And it gave me the following error:

**`ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /content`**

![Screenshot 2022-05-26 114140](https://user-images.githubusercontent.com/11463868/170428601-3ff92f55-de96-42ae-8d63-ae78ffeba440.png)

### **How can I fix this?**

.

**Comment by ravi-mosaicml** [comment]
Hi there!

Each command in colab is executed in its own shell, so the `cd` from the 2nd line isn't applying to the third line with the `pip install`. Instead, can you try combining the two -- like this?

```
!git clone https://github.com/mosaicml/composer.git
!cd composer && pip install -e ".[all]"
```

Let me know if this works. (I'll close the issue for now, but please re-open it if you are still running into an error)

**Comment by abdulsam** [comment]
@ravi-mosaicml Thank you for your response. 
I tried executing commands as you mentioned. But I think it leads to another error.

![Screenshot 2022-05-27 155239](https://user-images.githubusercontent.com/11463868/170682403-ceee5f1b-6dea-4950-a64c-6177fbc6c87f.png)

The error is: 
`ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/content/composer/setup.py'"'"'; __file__='"'"'/content/composer/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
`
