### ISSUE TITLE
RuntimeError- Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by abdulsam** [mosaicml/composer#1092]
I'm using **colab**.
I just tried to execute [Composer_Functional.ipynb](https://github.com/mosaicml/composer/blob/dev/notebooks/Composer_Functional.ipynb) cell by cell. 
After executing the following lines 

```
model = Net()
train_and_eval(model, trainloader, testloader)
```

I got the following error:

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument target in method wrapper_nll_loss_forward)`

Here is a snippet of that:

![Screenshot 2022-05-26 130854](https://user-images.githubusercontent.com/11463868/170456545-50b115f1-085d-4602-9640-48e497d2f2a0.png)

How can I resolve this issue?

**Comment by ravi-mosaicml** [comment]
Hi there!

It looks like we forgot some calls to set `y = y.to(device)`; thanks for catching this bug.

Here's a new notebook that should work:

https://githubtocolab.com/mosaicml/composer/blob/68a3f926b2d4dd771ca6e767c77b6c9d10051aae/notebooks/Composer_Functional.ipynb
