### ISSUE TITLE
BERT model_inputs raises Sequence Length Warmup error

### ISSUE THREAD

**Issue by alextrott16** [mosaicml/composer#1101]
https://github.com/mosaicml/composer/blob/875c1edd5da1ba89a036a174838690bc3c9fb79a/composer/algorithms/seq_length_warmup/seq_length_warmup.py#L199
This line in the sequence length warmup code checks that `model_inputs` includes `"labels"` and throws an error if it doesn't. This check is perhaps unnecessary and currently produces an error when using `BERTModel` because `"labels"` is removed from its `model_inputs` during initialization.

Current implementations seem to be built around the huggingface transformer that `BERTModel` wraps, where the output depends on whether the input batch includes labels. It seems undesirable that the type of output from the huggingface transformer depends on the structure of the batch.

Issues like this may motivate moving away from huggingface transformer modules in favor of our own implementations.

**Comment by hanlint** [comment]
This does seem extraneous as `model_inputs['labels']` is not used anywhere.. @moinnadeem can you confirm?

**Comment by mvpatel2000** [comment]
Closing because this is long dead
