### ISSUE TITLE
Remove `xfail` in `tests/algorithms/algorithm_settings` with a `simple_hf_settings` option

### ISSUE THREAD

**Issue by jzf2101** [mosaicml/composer#1118]
## 🚀 Feature Request

Per @ravi-mosaicml, can we build off of #992 and get rid of some of our `xfail` errors by adding some algorithm settings using our HF models?

https://github.com/mosaicml/composer/blob/f1862b8ebd4191a0ce6fc54d5a46ad5d0293451e/tests/algorithms/algorithm_settings.py#L192-L193

## Motivation

Right now we only have vision-related settings:

https://github.com/mosaicml/composer/blob/f1862b8ebd4191a0ce6fc54d5a46ad5d0293451e/tests/algorithms/algorithm_settings.py#L26-L49

**Comment by hanlint** [comment]
Yes, we should add canonical settings for NLP for each algorithm!

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri. We're open to community suggestions!
