### ISSUE TITLE
Consistency in docs [State, time, callbacks]

### ISSUE THREAD

**Issue by tcapelle** [mosaicml/composer#1172]
I am re-writing a callback that was working on composer 0.5 and now it does not.
I see that there is a new class `time` and that `state.epoch` is not there anymore, the problem is that the docs still point to that. Like [here](https://docs.mosaicml.com/en/v0.7.1/trainer/logging.html#logging-additional-data) or that `Logger` cannot be imported from `composer` (`from composer.loggers import Logger`)
I am having a hard time creating a custom callback, maybe a tutorial with the new API?

The callback is for logging images to wandb:
```python
import wandb
from composer import Callback, State, Logger

class LogPredictions(Callback):
    def __init__(self, num_samples=100, seed=1234):
        super().__init__()
        self.num_samples = num_samples
        self.data = []
        
    def eval_batch_end(self, state: State, logger: Logger):
        """Compute predictions per batch and stores them on self.data"""
        if state.epoch == state.max_duration: #on last val epoch
            if len(self.data) < self.num_samples:
                n = self.num_samples
                x, y = state.batch_pair
                outputs = state.outputs.argmax(-1)
                data = [[wandb.Image(x_i), y_i, y_pred] for x_i, y_i, y_pred in list(zip(x[:n], y[:n], outputs[:n]))]
                self.data += data
            
    def eval_end(self, state: State, logger: Logger):
        "Create a wandb.Table and logs it"
        columns = ['image', 'ground truth', 'prediction']
        table = wandb.Table(columns=columns, data=self.data[:self.num_samples])
        wandb.log({'sample_table':table}, step=int(state.timer.batch))
```

**Comment by ravi-mosaicml** [comment]
Hi there!

We removed `state.epoch`, `state.step`, and `state.timer`. Instead, for the epoch count, could you try using `int(state.timestamp.epoch)`, and for the batch count, `int(state.timestamp.batch)`? See the [Timestamp API Reference](https://docs.mosaicml.com/en/v0.7.1/api_reference/composer.core.time.html#composer.core.time.Timestamp) for more info.

We'll add the re-export of the `Logger` to composer to the next release; but for now, yes, could you use `from composer.loggers import Logger`.

Sorry for the confusion but thanks for letting us know -- we'll get it fixed!
