### ISSUE TITLE
Synthetic Data Generation for Brats Dataset

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#118]
Brats does not support synthetic data. It would be great to add support for it.

**Comment by ajaysaini725** [comment]
@ravi-mosaicml can you include more details on exactly what this entails? Right now, the `SyntheticDataset` class takes both a `data_shape` and a `label_shape` which can be used to generate synthetic data for BRATS.

**Comment by ravi-mosaicml** [comment]
To implement this:
1. Have brats inherit the `SyntheticHparamsMixin` class
2. If the `use_synthetic` flag is True, then the `initialize_object()` function should return a dataloader over synthetic data that can train. Here, you'll want to specify the data_shape and label_shape for the `SyntheticBatchPairDataset` . I am not sure what these parameters should be.

**Comment by mvpatel2000** [comment]
Closing as we don't plan on doing this anymore
