### ISSUE TITLE
Typographical error

### ISSUE THREAD

**Issue by roystonlmq** [mosaicml/composer#1213]
In README.md, 
under USAGE, there is an additional space after torch.nn.functional. It looks like: torch.nn.functional )

**Comment by hanlint** [comment]
Thanks for filing the issue! Upon looking, I think it might just be how markdown renders, the source code does not have any space:

https://github.com/mosaicml/composer/blob/8773fd867954cf3b3d34ec12df85537529356ba7/README.md?plain=1#L97-L99

Going to close this for now, please re-open if I misinterpreted your issue!
