### ISSUE TITLE
Fix flaky convergence unit test

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#124]
The trainer convergence test is flaky right now. This is likely due to the fact that we are using a CNN for the test which does significant dimensionality reduction and is thus hard to reason about in terms of linear separability of gaussian data. A fix would be to convert the test into training logistic regression. 

** To reproduce

Run the test many times on the same code (seems to fail once every ~50-100 times)

## Expected behavior

The test behavior should be consistent (i.e. if it passes once on some code then it should always pass on that code).

**Comment by ravi-mosaicml** [comment]
Closing the issue as we no longer have convergence tests.
