### ISSUE TITLE
Sample code for Progressive Image Resizing

### ISSUE THREAD

**Issue by abdulsam** [mosaicml/composer#1242]
Currently, I cannot see the example code for [Progressive Image Resizing](https://docs.mosaicml.com/en/stable/method_cards/progressive_resizing.html). Having that code available to developers would be beneficial.

Moreover, the help screen contains no coding examples.
![ProgressiveBatch](https://user-images.githubusercontent.com/11463868/176602639-8ac896b3-9f27-45ad-aee6-449f7c0c22b0.png)

I would appreciate it if you could provide an example of the coding involved.

**Comment by jfrankle** [comment]
Thank you so much for the feedback - we'll get this taken care of right away! In the meantime, you can find example uses of progressive resizing (and all of our other speedup methods) in our [algorithm documentation](https://docs.mosaicml.com/en/latest/trainer/algorithms.html). We have a method card written for each of our speedup methods, including example code, data, and technical commentary. [You can find the one for progressive resizing here.](https://docs.mosaicml.com/en/latest/method_cards/progressive_resizing.html).

Please keep us posted on how things go and how we can continue to improve our documentation!

**Comment by mvpatel2000** [comment]
Looks like this was closed [here](https://github.com/mosaicml/composer/pull/1340)
