### ISSUE TITLE
Implement warmup_ratio for learning rate warmup

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#125]
Papers often describe the linear warmup in terms of a percentage of the total training time (i.e. "We warmup for 1% of the total training duration, 5% of the total training duration, etc). Currently, a user has to do the math manually to compute the warmup. It isn't hard, but it's just inconvenient. It would be great if we could add a `warmup_ratio` hparam to the warmup schedule, which can calculate this for us.

**Comment by ravi-mosaicml** [comment]
Fixed via #463 and #146
