### ISSUE TITLE
Implement ESAM

### ISSUE THREAD

**Issue by jbloxham** [mosaicml/composer#13]
[Efficient SAM](https://openreview.net/forum?id=n0OeTdNRG0Q) (anonymous, 2022) is a proposed duo of SAM optimizations to reduce the throughput hit of SAM. The composer repo already supports an `interval` hyperparameter which has empirically been found to maintain much of the quality improvement of SAM while sacrificing little throughput, but it would be interesting to see if ESAM could enable setting lower values of `interval`.

**Comment by mvpatel2000** [comment]
Closing because it's not on our roadmap
