### ISSUE TITLE
Missing API links from method pages

### ISSUE THREAD

**Issue by JJGO** [mosaicml/composer#1330]
First, thanks for developing this great library

I was digging through the composer docs because I wanted to test out blurpool. While the [Method entry](https://docs.mosaicml.com/en/stable/method_cards/blurpool.html) is great (has examples for both Trainer and Functional as well as great discussion about the technical details), it is quite unintuitive how to get to the API since it isn't linked in the page. This is a bit bothersome as the algorithm signature is not included either so it's not obvious what the possible parameter options and/or default values are.

Moreover I feel it's not obvious how to get to the API docs either. I.e. for blurpool you have to:

1. find the API Reference link at the bottom (not obvious at first)
2. go to algorithms
3. go to composer.algorithms.blurpool 
4. go to composer.algorithms.blurpool.blurpool.

I saw that issue #713  in the repo mentions this, but it's still open and the docs still have no pointers to the API. So yeah, just my 2ct that this kinda hurts navigation of the library, as I now default to my IDE to quickly navigate to the source to take a look at the docstring and kwargs instead of using the published docs.

**Comment by hanlint** [comment]
Thanks @JJGO , agreed we'll add the API docs to the method cards, that's' probably the easiest entrypoint.

Unfortunately the nested `composer.algorithms.blurpool.blurpool` is difficult to solve unless we either (1) resort to some sphinx ninja magic, or (2) manually maintain the list of algorithms (e.g. the pytorch approach).
