### ISSUE TITLE
Modify max_epochs to support a time abstraction

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#134]
## 🚀 Feature Request
Currently, we support max_epochs to determine how long to train for. This breaks under an abstraction where the user wants to train for a certain number of samples (which could result in ~3.5 epochs). We should update max_epochs to be max_iters, and values can use the time abstraction to be `3ep` or `3131ba` (as an example).

## Motivation
A user wants to train for fractions of an epoch. How do they do this? In other words, they want to train for a fixed number of steps instead of a fixed number of epochs.

**Comment by ravi-mosaicml** [comment]
Closing for #146
