### ISSUE TITLE
Apparent throughput decrease

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#136]
**Environment**
- Hardware (GPU, or instance type): GCP 8x A100 (`a2-highgpu-8g-a100-8`), AWS 8x T4 (`g4dn.metal`)
- Composer branch: `main`
- Docker image: `mosaicml/composer:latest`; `mosaicml/composer:all-0.2.4` 

**To reproduce**

1. `mctl -f data_collection/aug_blog_r50_baseline.yaml --name test` in [this research2.0 branch](https://github.com/mosaicml/research2/tree/matthew/augmentations_test); or anything that calls `run_mosaic_trainer.py`
2. View throughput logs in W&B

## Expected behavior

Throughput for baseline and channels last-only should be ~9k im/sec on 8x A100 ([see timing runs on W&B](https://wandb.ai/mosaic-ml/avery-data-resnet50-gcp-a100-timing/table?workspace=user-mleavitt)) and ~2k im/sec on 8x T4 ([see timing runs on W&B](https://wandb.ai/mosaic-ml/avery-data-resnet50-aws-t4-timing?workspace=user-mleavitt))

## Additional context

8x A100 throughput seems to be ~ 6500 im/sec for channels last for [Matthew's runs](https://wandb.ai/mosaic-ml/matthew-augblog?workspace=user-mleavitt), and ~3500 im/sec for [Tyler's runs](https://wandb.ai/mosaic-ml/tyler-0.3.0-rc/table?workspace=user-tylerlee).

8x T4 throughput is [~1300 im/sec](https://wandb.ai/mosaic-ml/tyler-0.3.0-rc/runs/wpp8z3fn?workspace=user-tylerlee).

Tyler is awaiting runs to confirm that the throughput decrease is reproducible on AWS.

**Comment by abhi-mosaic** [comment]
@growlix Acknowledged, will profile the dataloader to see if that's the issue and follow up from there

**Comment by growlix** [comment]
@siriuslee and @bandish-shah determined that this is caused by the wrong version of Pillow overwriting Pillow-SIMD when Composer is installed (e.g. via `pip install -e .`). Fix currently in progress from @bandish-shah.

**Comment by ravi-mosaicml** [comment]
#182 pre-installs a pillow stub and pillow-simd, so this issue should be resolved. #191 added a test case to ensure that we're using pillow-simd.
