### ISSUE TITLE
[Q] How do the schedulers work with resume / interrupt?

### ISSUE THREAD

**Issue by vedantroy** [mosaicml/composer#1384]
If I have a `CosineAnnealingWithWarmupScheduler` with `t_warmup=500ba, t_max=1000ba`, and I have a training run that goes for `1500ba` and saves checkpoints. Let's say the run finishes. And now, I restart the run from the final checkpoint for another 1500 batches. Will the learning rate be 0 the entire time, or will it restart the cosine annealing process (with warmup)?

**Comment by hanlint** [comment]
You are welcome to test this, but it should stay at 0. We simply load up all the state (including the scheduler state), and continue training, as if you had trained for `3000ba` to begin with.
