### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by ananyahjha93** [mosaicml/composer#1430]
Just some documentation update required. I think there is a mixup between documentation for Factorize, FusedLayerNorm and GatedLinearUnits.

![image](https://user-images.githubusercontent.com/7491256/185704712-a0fda4f9-48b6-4a92-8194-3b5b639e6c4d.png)

**Comment by growlix** [comment]
Good find, Ananya! Will add this to the soon-to-be-released documentation update!
