### ISSUE TITLE
CUDA graph integration

### ISSUE THREAD

**Issue by ananyahjha93** [mosaicml/composer#1439]
## 🚀 Feature Request

Integrate cuda graph speedup with composer trainer.
https://pytorch.org/blog/accelerating-pytorch-with-cuda-graphs/

## Motivation

Since composer focuses quite a bit on speedups, integrating cuda graphs makes sense to me. Also, checking if existing models benefit from introducing this speedup.

Maybe a better proposal will be to first check if the existing models benefit from using cuda graphs, and then if they do, integrating them into composer might be a good idea.

**Comment by hanlint** [comment]
cc: @dskhudia who is looking into CUDA graphs, torch dynamo, torch fx, XLA, and all the fun performance tools, for a comment here.

**Comment by dskhudia** [comment]
@ananyahjha93 , Thanks for point this out. This has been on our radar for a while but hasn't bubbled up in priority yet. 

CUDA graphs benefit the most when things are CPU bound or we are launching a lot of kernels each with little work. Currently such typically smaller models hasn't been a primary use case for Composer. 

[Nvidia reported 6% improvement with CUDA Graphs](https://github.com/mlcommons/training_results_v1.1/blob/main/MLPerf%20Training%201.1%20Submitter%20Summaries.pdf) for their previous MLPerf results. It's not much so I think finding a good use case is the key for prioritizing support for CUDA graphs. 

> CUDA graphs were expanded to encompass the entire iteration, improving performance by 6%
on ResNet-50

If you know a particular use case you are interested in that benefits from CUDA graphs, please let us know.

**Comment by ananyahjha93** [comment]
@dskhudia hey, I wasn't aware that you had already benchmarked CUDA graphs, but yes from what you mention it doesn't seem to be that beneficial to prioritize it.

feel free to close this issue then!

**Comment by dskhudia** [comment]
@ananyahjha93 I, myself, didn't benchmark but have seen these numbers from NVidia/PyTorch blogs.
