### ISSUE TITLE
Inconsistency in Return Value of Functional Algorithms

### ISSUE THREAD

**Issue by nik-mosaic** [mosaicml/composer#1441]
## 🚀 Feature request
Some algorithms return the `model` at the end of the apply_algorithm() function, others return None. It is not obvious to the user if there is a reason behind this, and why the return types are not consistent.

E.g.
Returns model:
- [Batchnorm](https://github.com/mosaicml/composer/blob/dev/composer/algorithms/ghost_batchnorm/ghost_batchnorm.py)
- [Blurpool](https://github.com/mosaicml/composer/blob/dev/composer/algorithms/blurpool/blurpool.py#L24)
etc.

Do not return anything:
- [LayerNorm](https://github.com/mosaicml/composer/blob/dev/composer/algorithms/fused_layernorm/fused_layernorm.py#L42)
- [Gated Linear Units](https://github.com/mosaicml/composer/blob/dev/composer/algorithms/gated_linear_units/gated_linear_units.py#L58)
etc.

## Motivation
In some cases a user could type `model = apply_algorithm(model)` and it will succeed as expected, and in other cases it will silently cause model to equal None. Without looking at the source code, the user will not know why.

## Solution
Add `return model` to the end of every algorithm that currently returns None.

**Comment by mvpatel2000** [comment]
Closed as done
