### ISSUE TITLE
EMA missing from the Methods Overview page

### ISSUE THREAD

**Issue by priyamdey** [mosaicml/composer#1494]
Hi there,

A feedback on the doc: [EMA](https://docs.mosaicml.com/en/v0.9.0/method_cards/ema.html) is not present as a card in the [Methods Overview](https://docs.mosaicml.com/en/v0.9.0/method_cards/methods_overview.html) page. I'm looking at the doc version 0.9.0.

Thanks

**Comment by mvpatel2000** [comment]
Thanks for pointing this out! We're redesigning that page, and it should be fixed in this [PR](https://github.com/mosaicml/composer/pull/1436)
