### ISSUE TITLE
Search doesn't work in docs with 0.10.0 release

### ISSUE THREAD

**Issue by ananyahjha93** [mosaicml/composer#1556]
** Environment **
NA

** To reproduce

Go to Composer docs and try to search for anything.
<img width="782" alt="Screen Shot 2022-09-23 at 6 46 16 AM" src="https://user-images.githubusercontent.com/7491256/191975221-8513cdb8-971c-4a6d-a0cc-0d7f697fd0cf.png">

<img width="714" alt="Screen Shot 2022-09-23 at 6 46 30 AM" src="https://user-images.githubusercontent.com/7491256/191975238-2bcd9df3-eb41-4f92-95c7-834de42b774e.png">

**Comment by hanlint** [comment]
Thanks @ananyahjha93 , we ran the crawler today on the updated site, and this should now be fixed!
