### ISSUE TITLE
CheckpointSaver take Path object along with str

### ISSUE THREAD

**Issue by ilee300a** [mosaicml/composer#1573]
## 🚀 Feature Request
Currently CheckpointSaver only takes strings for folder and file names, but it would be nice for it to also take Path objects.

## Motivation
Those attributes are ultimately converted to path objects. When creating a child class from the CheckpointSaver, when we call the parent's initializer, we have to cast all of those back to strings

**Comment by eracah** [comment]
Hi @ilee300a,
That is a great idea! We are currently refactoring the CheckpointSaver and will add that to our plan.

**Comment by eracah** [comment]
Hey,  @ilee300a, this didn't quite make it into v0.11, but we'll do a hotfix this week and add it!
