### ISSUE TITLE
Handle Miscellaneous / Extra Keys in load_state_dict

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#158]
# Problem
For fine-tuning on GLUE tasks, the user wants to load a pre-trained BERT model checkpoint into a model that has a BERT network + a task-specific classification head. Therefore, the model architecture for the pre-trained checkpoint and current BERT model architecture will differ slightly. This yields the following error:

```
Traceback (most recent call last):
  File "examples/run_mosaic_trainer.py", line 47, in <module>
    main()
  File "examples/run_mosaic_trainer.py", line 42, in main
    trainer = Trainer.create_from_hparams(hparams=hparams)
  File "/mnt/gcp/moin/composer/composer/trainer/trainer.py", line 372, in create_from_hparams
    trainer = cls(
  File "/mnt/gcp/moin/composer/composer/trainer/trainer.py", line 326, in __init__
    self.checkpoint_loader.load_checkpoint(state=self.state)
  File "/mnt/gcp/moin/composer/composer/trainer/checkpoint.py", line 35, in load_checkpoint
    state.load_state_dict(self.state_dict["state"])
  File "/mnt/gcp/moin/composer/composer/core/state.py", line 192, in load_state_dict
    state_value.load_state_dict(serialized_value)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BERTModel:
        Missing key(s) in state_dict: "module.classifier.weight", "module.classifier.bias".
Error in subprocess
```

This isn't a Composer error, it's from PyTorch. In order to permit that the architectures could differ, they have introduced a flag `strict` which will continue loading the checkpointed weights even if the keys do not perfectly align. It is important to note that the `strict` flag can also cause some easy-to-forget bugs in a workflow.

## Suggested Solutions
1. Add a `strict_checkpointing` parameter in the YAML for checkpointing, and use that to set the `strict` flag in load_state_dict. If the dictionaries mismatch, that is the user's fault.
2. Add a `strict_checkpointing` parameter in the YAML for checkpointing, and use that to set the `strict` flag in load_state_dict. Additionally, print the set of differences in the two strings with a warning. 

For instance, `WARNING: The model has XYZ keys that the checkpoint does not have, and the checkpoint has XYZ keys that the model does not have. This may cause errors in your training setup.`

3. Add a `strict_checkpointing` parameter in the YAML for checkpointing, and use that to set the `strict` flag in load_state_dict. Additionally, add a `missing_keys` and `unexpected_keys` that permits the user to explicitly set the differences they expect when loading the checkpoint. This is very safe, but might be too much work for a user. I do enjoy how they have to explicitly set those differences in a "opt-in" manner.

**Comment by ravi-mosaicml** [comment]
I'd be for #2 or #3. Probably #2. I presume that if `strict` is True, and keys mismatch, then an error would be raised? If `strict` is False, then the warning would be emitted.

**Comment by moinnadeem** [comment]
Sounds good @ravi-mosaicml , I'll submit a PR with #2 implemented shortly.

**Comment by ravi-mosaicml** [comment]
Closing since #169 implements and fixes this.
