### ISSUE TITLE
Load a checkpoint without loading its associated state

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#159]
When we load a checkpoint, it restores all of the associated state (`train_batch_size`, `test_batch_size`, `optimizers`, etc). This is undesired for when a user just wants to initialize the model with a new pre-trained checkpoint, instead of continuing to train from a previous snapshot. 

We might need to bifurcate these two use cases, potentially.

**Comment by ravi-mosaicml** [comment]
I think this could best be done by adding `CheckpointLoaderHparams` to control which fields from the specified checkpoint file should be loaded, but am not sure about how granular this should be...e.g. can you load some algorithms but not others?

**Comment by moinnadeem** [comment]
There are two proposed solutions here:

1) Create a `CheckpointLoader` hparams object, that has two fields: `checkpoint_filepath` and `load_weights_only`. `load_weights_only` would only recover the model weights and avoid restoring the rest of the checkpointed state. Additionally, this would help us bifurcate on when to use `strict` on restoring the model weights: we never want `strict=False` if restoring state as well.

2) Create a `CheckpointLoader` hparams object that provides significant granularity over the checkpointing process. It would be able to toggle which parts of the state should/shouldn't be recovered, and have fields such as `restore_optimizers`, `restore_batch_sizes`, restore_step`, `restore_algorithms`, `restore_callbacks`, etc. This is the more general, albeit more implementation-heavy solution.

I am curious for what people think.

**Comment by ravi-mosaicml** [comment]
Closing since #169 is merged
