### ISSUE TITLE
Resume DDP training with a checkpoint

### ISSUE THREAD

**Issue by priyamdey** [mosaicml/composer#1664]
** Environment **

PyTorch version: 1.12.1
Torchvision version: 0.13.1
CUDA used to build PyTorch: 11.3

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (conda-forge gcc 10.4.0-16) 10.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.13
Python platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB

Nvidia driver version: 450.80.02

Composer information
--------------------
Composer version: 0.9.0
Host processor core count: 64
Number of nodes: 1
Accelerator model name: A100-SXM4-40GB
Accelerators per node: 1
CUDA Device Count: 4

** To reproduce

1. Clone the codebase provided in the link below. 
2. Use run.sh to resume DDP run with the checkpoint provided. 
3. It shouldn't resume, throwing OOM error.
4. It doesn't throw any OOM when the training is very short (5ep or 10ep), but does when it trains for longer (40ep or 100ep). One can try testing this by changing the appropriate variables in the run.sh file

## Expected behavior

It should resume with the checkpoint normally without any errors.

## Additional context

codebase: [link](https://github.com/priyamdey/ddp-resume-mosaic)
checkpoint (100ep total training, dumped at 88ep):  [link](https://drive.google.com/file/d/1U5bbI5RMCYJv7bM_KwjUNQQdhCyctKwB/view?usp=sharing)

**Comment by eracah** [comment]
Hi, @priyamdey, thanks for the repro repo! Interesting issue. Is there any way you can share your error logs? Also, another thing that might help is upgrading to composer v0.11. We fixed a few checkpointing related issues there.

**Comment by priyamdey** [comment]
Hi @eracah , where do I find the error logs? And you want the one when I'm loading the checkpoint? I can try shifting to v0.11, but does that change any sort of training behavior?

**Comment by priyamdey** [comment]
Hi @eracah , I tried testing the same with v0.11, unfortunately getting a similar OOM behavior there as well:

(Note: Ihad to update for some breaking changes like LogLevel, comment out missing algo check in the state.py to bypass repr error)

<details>
<summary>Details</summary>

```
512
[
trace]: algorithm_traces/ChannelsLast/Event.INIT:1
[trace]: algorithm_traces/BlurPool/Event.INIT:1

******************************
Config:
blurpool/num_blurconv_layers: 6
blurpool/num_blurpool_layers: 1
enabled_algorithms/BlurPool: true
enabled_algorithms/ChannelsLast: true
enabled_algorithms/HeadAdder: true
enabled_algorithms/ProgressiveResizing: true
num_gpus_per_node: 2
num_nodes: 1
rank_zero_seed: 42

******************************
ERROR:composer.cli.launcher:Rank 1 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Global rank 1 (PID 812356) exited with code 1
----------Begin global rank 1 STDOUT----------

----------End global rank 1 STDOUT----------
----------Begin global rank 1 STDERR----------

[trace]: algorithm_traces/ChannelsLast/Event.INIT:1
[trace]: algorithm_traces/BlurPool/Event.INIT:1
Traceback (most recent call last):
  File "ddp-resume-mosaic/main.py", line 198, in <module>
    main(args)
  File "ddp-resume-mosaic/main.py", line 188, in main
    trainer.fit()
  File "python3.9/site-packages/composer/trainer/trainer.py", line 1601, in fit
    self._train_loop()
  File "python3.9/site-packages/composer/trainer/trainer.py", line 1711, in _train_loop
    self._spin_dataloaders()
  File "python3.9/site-packages/composer/trainer/trainer.py", line 1672, in _spin_dataloaders
    for _ in dataloader:
  File "python3.9/site-packages/ffcv/loader/loader.py", line 214, in __iter__
    return EpochIterator(self, selected_order)
  File "python3.9/site-packages/ffcv/loader/epoch_iterator.py", line 55, in __init__
    memory_allocations[p_id] = p.allocate_memory(self.loader.batch_size,
  File "python3.9/site-packages/ffcv/pipeline/pipeline.py", line 103, in allocate_memory
    allocated_buffer = self.allocate_query(memory_allocation,
  File "python3.9/site-packages/ffcv/pipeline/pipeline.py", line 73, in allocate_query
    partial = ch.empty(*final_shape[1:],
RuntimeError: CUDA out of memory. Tried to allocate 182.00 MiB ...
```

</details>

**Comment by mvpatel2000** [comment]
After discussing this offline, it seems like the issue was related to FFCV dataloaders. Spinning the dataloader, which sets the epoch for the distributed sampler and fetches a single sample to fix the randomness, led to OOM. I was unable to reproduce this with any other dataloader, so I am reasonably confident it is an FFCV problem. 

Because of this, I'm going to close out this issue. If anything new is found, please feel free to reopen this!
