### ISSUE TITLE
Eval Interval without a Validation Dataloader

### ISSUE THREAD

**Issue by TrentBrick** [mosaicml/composer#1788]
I am using multiple datasets, some with validation dataloaders and some without. 

When I pass `None` for a validation dataloader but keep the rest of my `Trainer` the same I get the error: 

```Specifying `eval_interval` without an `eval_dataloader` has no effect.```

I have tried setting `eval_dataloader` to `0`, `None` but nothing seems to work...

Thanks, 
Trenton

**Comment by mvpatel2000** [comment]
Btw, we've opened a PR in dev https://github.com/mosaicml/composer/pull/1791 to update the error messages so they're more helpful

**Comment by TrentBrick** [comment]
@mvpatel2000 thanks for this. So if I need to set a value I can set =1 (even though I am not passing in an eval dataloader?)

**Comment by TrentBrick** [comment]
Nope it failed. Still getting: 

`ValueError: Specifying `eval_interval` without an `eval_dataloader` has no effect.`

**Comment by TrentBrick** [comment]
This is when I am passing in `None` for the val_dataloader

**Comment by mvpatel2000** [comment]
@TrentBrick could you potentially share more of your code? Here is the code that controls this error:
https://github.com/mosaicml/composer/blob/release/v0.11.1/composer/trainer/trainer.py#L1093-L1097
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17102158/207198516-49791c0b-a65c-4ff2-b0e2-ebd5ae631a7c.png">
so I'm not sure why you're still hitting it if you're specifying `eval_interval=1`. I'm assuming you're on the most recent release (0.11.1)

**Comment by TrentBrick** [comment]
```
if "no_validation" in params and params.no_validation: 
        dataloaders['val'] = None
    else:
        dataloaders['val'] = dataloader_fn(params, 
            data_path,train_or_val="val"),

---

if "no_validation" in params and params.no_validation:
        params.eval_interval_str = 1

---

trainer = Trainer(
            ...,
            eval_dataloader=dataloaders['val'],
            eval_interval=params.eval_interval_str,
)
```

**Comment by mvpatel2000** [comment]
@TrentBrick would you mind providing a minimal repro? Happy to help debug with one.

**Comment by TrentBrick** [comment]
Ok in making a minimal repro I figured out that my tester script (rather than parallelized runner) hadn't updated with the entry of "1". Now things work. Sorry for the confusion.

**Comment by mvpatel2000** [comment]
great! glad its working. Feel free to reach out if you hit any other issues
