### ISSUE TITLE
Ray Idles after successful run

### ISSUE THREAD

**Issue by TrentBrick** [mosaicml/composer#1816]
I am using Ray to start multiple runs. 

After a successful run, the ray nodes all idle consuming RAM. eg. calling `nvidia-smi` gives `0   N/A  N/A     60895      C   ray::IDLE                        1177MiB |`

This was not the case for Pytorch Lightning. 

What am I missing? 
```

def start_experiment(exp_ind):
    ... Other commands ...
    temp_trainer.fit()
    wandb.finish()

out = ray.get([start_experiment.remote(exp_ind) for exp_ind in range(len(job_script.exp_list)) ])
ray.shutdown()

```

**Comment by mvpatel2000** [comment]
We spotted a bug recently related to memory freeing https://github.com/mosaicml/composer/pull/1769 which was patched in dev (and should be released in ~1 week). I suspect it's likely that? If this is blocking, you could try dev, but otherwise it should be addressed soon. If it doesn't go away after, happy to take a deeper look!

**Comment by TrentBrick** [comment]
Not blocking but very annoying! Need to run `pkill ray` after every run... Glad it's getting patched, thanks. Should I be installing from GitHub then instead of pip in a week?

**Comment by mvpatel2000** [comment]
> Should I be installing from GitHub then instead of pip in a week?

Nope! We'll do a pypi release with 0.12

**Comment by mvpatel2000** [comment]
I'll leave this issue open until release. If you can confirm it works after, that would be great -- I'll close it after.

**Comment by TrentBrick** [comment]
Testing this now but think I'm going to bail from Mosaic. Too many issues.

**Comment by mvpatel2000** [comment]
> Testing this now but think I'm going to bail from Mosaic. Too many issues.

If you have any feedback on things that could be better or other issues, please feel free to let us know!
