### ISSUE TITLE
Implement "timing runs" as runs w/  very small SSR & subsampled data

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#186]
## 🚀 Feature Request
Implement "timing runs" as convergence runs with a small SSR and a dataset subsampling (e.g. SSR 0.15 and 100k data samples?).

## Motivation

We've already seen that timing runs for progressive resizing reported inaccurate throughput numbers. This problem may arise again for other epoch-variable algorithms. Implementing timing runs as convergence runs w/ small SSR and dataset subsampling would likely avoid future headaches.

## [Optional] Implementation

"Timing runs" could just be a .yaml with small SSR (e.g. 0.15) and dataset subsampling. This would require implementing dataset subsampling, which should probably be a part of our dataloader anyway.

Note: This has been discussed on slack, and @ajaysaini725 seems to be taking point on a solution. Just putting it here for posterity.

**Comment by ravi-mosaicml** [comment]
Would the `train_subset_num_batches` and/or `eval_subset_num_batches` in the trainer hparams accomplish this?

**Comment by growlix** [comment]
Yes, that seems like a straightforward way to do it!

**Comment by ravi-mosaicml** [comment]
Sg! Going to close this issue.
