### ISSUE TITLE
LION: evoLved sIgn mOmeNtum

### ISSUE THREAD

**Issue by rahulvigneswaran** [mosaicml/composer#1975]
## New Method
**tldr:** EvoLved Sign Momentum, new optimizer discovered by Google Brain that is purportedly better than Adam(w), in Pytorch.
**Code:** https://github.com/lucidrains/lion-pytorch, https://github.com/google/automl/blob/master/lion/lion_pytorch.py
**Paper:** https://arxiv.org/abs/2302.06675

## Motivation
https://github.com/lucidrains/lion-pytorch/blob/main/README.md

## Attribution
[Xiangning Chen](https://arxiv.org/search/cs?searchtype=author&query=Chen%2C+X), [Chen Liang](https://arxiv.org/search/cs?searchtype=author&query=Liang%2C+C) (https://github.com/crazydonkey200)

**Comment by mvpatel2000** [comment]
Apologies for the late reply. Composer can accept arbitrary optimizers, so you should be able to use LION if you wish. For example, we do use it in our `examples` repo https://github.com/mosaicml/examples/blob/main/examples/common/optim/lion.py
