### ISSUE TITLE
Checkpoint Memory Management

### ISSUE THREAD

**Issue by jbloxham** [mosaicml/composer#204]
We want to start checkpointing with DeepSpeed on some very memory/disk-constrained machines. It's suspected that, as the amount of checkpoints stored on the machine currently grows linearly with time, we might run out of space in cases where the model is very large, as will be the case for LLMs. First, we need to verify this is actually a problem. Assuming so, the solution would be to keep a cap on the amount of checkpoints stored locally, or delete checkpoints after they have been uploaded to cloud.

**Comment by ravi-mosaicml** [comment]
Great point, this makes sense.

From an implementation perspective, it would be much cleaner to limit the # of checkpoints stored locally, as the it can be risky deleting from the run directory. The run directory uploader doesn't know whether a file is still being used (though it could query the kernel to see if it has an open FD?) or whether a file in the run directory maybe need to be read later (say, by another run directory reader, such as the wandb artifact uploader)

**Comment by ravi-mosaicml** [comment]
I presume this will be addressed in the checkpoint refactor.

**Comment by ravi-mosaicml** [comment]
Need to add a `num_checkpoints_to_keep` argument to the CheckpointSaver callback, after #421 is finished. (The run directory abstraction assumes that files will never be deleted, so we need to remove the run directory first.)
