### ISSUE TITLE
`pip install composer==0.13.1` leads to no metadata for composer env.

### ISSUE THREAD

**Issue by samuelstevens** [mosaicml/composer#2048]
**Environment**

I can't run `composer_collect_env` because there is no package data found for `mosaicml`.
This causes bugs when checkpointing as well.

**To reproduce**

1. Make a new virtual env.
2. `pip install composer==0.13.1`
3. `composer_collect_env`

## Expected behavior

It works.

## Additional context

```
def get_composer_commit_hash() -> Optional[str]:
    # Use PEP-610 to get the commit hash                                                          
    # See https://packaging.python.org/en/latest/specifications/direct-url/
    files = importlib_metadata.files('mosaicml') # <= change this to 'composer'
    if files is None:
        return
    files = [f for f in files if str(f).endswith('direct_url.json')]
    if len(files) == 0:
        return
    f = files[0]
    direct_url = json.loads(f.read_text())
    vcs_info = direct_url.get('vcs_info', {})                                                     
    commit_id = vcs_info.get('commit_id')
    return commit_i
```

I can open a PR if you like.

**Comment by dakinggg** [comment]
Hey @samuelstevens thanks for the report, and sorry about that! We'll get this fixed ASAP. In the meantime, you should still be able to use `pip install mosaicml`.

**Comment by bandish-shah** [comment]
The `composer==0.13.1` PyPi package has been yanked, thanks for reporting this!
