### ISSUE TITLE
Less strict numpy version pinning

### ISSUE THREAD

**Issue by fgerzer** [mosaicml/composer#2105]
## 🚀 Feature Request
Allow for newer numpy versions than `<1.23.0`.

## Motivation

Currently, composer fixes numpy to be `'numpy>=1.21.5,<1.23.0'`. This is unfortunate, because other requirements that we use need numpy > 1.23.0, creating an incompatibility.

This was set in #1345 in reaction to a build failure because scipy need(ed) `<1.23.0`. Scipy itself is apparently pulled from `torch-metrics`. 

I don't believe this is current anymore:
- composer pulls in `torchmetrics>=0.10.0,<0.11.4`
- torchmetrics 0.11.3 pulls in `scipy >1.0.0, <=1.10.0` [(requirements)](https://github.com/Lightning-AI/metrics/blob/v0.11.3/requirements/image.txt#LL4C23-L4C23)
- scipy 1.10.0 sets `np_maxversion = '1.27.0'` [(setup.py)](https://github.com/scipy/scipy/blob/v1.10.0/setup.py#L453)

Indeed, scipy has https://github.com/scipy/scipy/issues/16964, which was fixed in https://github.com/scipy/scipy/pull/16966 in September of 2022, while #1345 above was noted in August.

Accordingly, it looks like relaxing the numpy maxversion should have a valid requirements path. 

The closed PR https://github.com/mosaicml/composer/pull/1835 would already implement this.

**Comment by dakinggg** [comment]
Hey @fgerzer thanks for raising this! Good chance we can safely upgrade numpy; will test it out.

**Comment by fgerzer** [comment]
Nice, thank you for fixing this! I've already run trainings with numpy 1.24, and unsurprisingly encountered no issues either.
