### ISSUE TITLE
Image in Documentation Not Loading

### ISSUE THREAD

**Issue by ez2rok** [mosaicml/composer#2106]
In the documentation for gated linear unit [here](https://docs.mosaicml.com/en/latest/method_cards/gated_linear_units.html), the image of the gated linear unit is not loading. 

Inspecting the HTML code reveals that the image is stored at [this url](https://storage.cloud.google.com/docs.mosaicml.com/images/methods/gated_linear_units.png) which works perfectly fine and it actually displays the following image:
![image](https://user-images.githubusercontent.com/69025426/228580504-f7710ea0-98db-475d-8e41-ec9ca4043286.png)
which seems to be the correct image.

I don't know why the image is not loading in this case. Any ideas?

**Comment by lupesko** [comment]
Loading the docs URL ([Gated Linear Unit](https://docs.mosaicml.com/en/latest/method_cards/gated_linear_units.html)) in incognito mode, I can reproduce the issue and see the 403 when the browser tries to load the image from [this google cloud storage location](https://storage.cloud.google.com/docs.mosaicml.com/images/methods/gated_linear_units.png).

@bandish-shah - can you look into the permission set for the image?
