### ISSUE TITLE
Pytorch 2.0 support

### ISSUE THREAD

**Issue by djwessel** [mosaicml/composer#2147]
Now that PyTorch 2.0 has been officially released, I was wondering when composer will officially support it? Currently the library only supports `torch>=1.10.0,<1.14`.

**Comment by dskhudia** [comment]
We have an alpha support coming in soon in dev. See https://github.com/mosaicml/composer/pull/2118/ for more details. This is alpha because we have still done limited testing but works for models HF bert/Resnet.
