### ISSUE TITLE
Broken cod

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/composer#2168]
Training loop image is missing from the docs page https://docs.mosaicml.com/projects/composer/en/latest/examples/custom_speedup_methods.html: ![image](https://user-images.githubusercontent.com/8884008/234281217-d99debdc-5e3b-410e-ae99-5a4e65afd570.png)

(it is a very important reference point when implementing custom algorithms in composer)

**Comment by eracah** [comment]
Should be fixed now, @eldarkurtic !
