### ISSUE TITLE
[Question] Does this work with Torchrun in a distributed manner?

### ISSUE THREAD

**Issue by Data-drone** [mosaicml/composer#2194]
Is it possible to use Composer in a distributed setting with `torchrun` ?

**Comment by mvpatel2000** [comment]
We generally recommend you use our distributed launcher, which you can check out in the docs [here](https://docs.mosaicml.com/projects/composer/en/latest/notes/distributed_training.html#usage). Something like:
`composer my_script.py` would work.

With that said, I expect `torchrun` should work. If, for some reason, you strongly prefer that, please feel free to try it out! We're happy to provide assistance if you hit any errors.

**Comment by mvpatel2000** [comment]
Closing given above answer
