### ISSUE TITLE
SeqLengthWarmup for non-HuggingFaceModel?

### ISSUE THREAD

**Issue by tbenthompson** [mosaicml/composer#2213]
Currently, the SeqLengthWarmup algorithm requires the model to be a HuggingFaceModel. Is this restriction necessary?

```
RuntimeError: SeqLengthWarmup requires state.model to be of type HuggingFaceModel, not of type <class 'project.composer_model.Model'>
```

Thanks!!

**Comment by dakinggg** [comment]
I believe the actual requirement is actually that the _batch_ is in the expected format of a huggingface model, and it likely works with any model (except for the runtimeerror you hit).

**Comment by dakinggg** [comment]
If you'd like to test this out and open a PR, we're always happy to take contributions :)

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri. We're open to community suggestions!
