### ISSUE TITLE
[Question & Doc Typo] What's the difference between ComposerModel.get_metrics() and ComposerModel.metrics()?

### ISSUE THREAD

**Issue by alckasoc** [mosaicml/composer#2219]
### Question 
* `composer.ComposerModel.get_metrics()`
* `composer.ComposerModel.metrics()`

I was planning on implementing the `get_metrics` method for `ComposerModel`, but upon reading through the documentation for `ComposerModel`, I noticed there were 2 methods: `get_metrics` and `metrics`. They both have similar parameters: `is_train` and `train`, and though they have similar (yet different) outputs, the documentation still felt a bit unclear.

Why are there 2 similar methods and what are their differences? 

### Typo
Unrelated, this might be a bit nitpicky, but I also found a small typo in [this page](https://docs.mosaicml.com/projects/composer/en/latest/trainer/evaluation.html). Why do the 2 methods have different parameter names?
![image](https://github.com/mosaicml/composer/assets/58043265/63e8ec53-a5e1-4365-8a99-884d183afdb5)

```py
metrics = model.get_metrics(is_train=False)
```
The first line's parameter is changed from `train` to `is_train` as per:

![image](https://github.com/mosaicml/composer/assets/58043265/e7d4db22-c9b3-4781-a200-66a65861735c)

Much appreciated! 😄

**Comment by dakinggg** [comment]
Hi @alckasoc, the `metrics` function is deprecated (https://github.com/mosaicml/composer/blob/457717427e4d84f645e04fd801e79ab45fd26877/composer/models/base.py#L199-L202) and will be removed. You can use `get_metrics` :) Thanks!
