### ISSUE TITLE
Use the nvidia-supplied nvidia-ml-py instead of pynvml

### ISSUE THREAD

**Issue by abhi-mosaic** [mosaicml/composer#2232]
## 🚀 Feature Request
Remove `pynvml` and use [nvidia-ml-py](https://pypi.org/project/nvidia-ml-py/) instead.

## Motivation
Based on this issue in the LLM Foundry, we should probably use the NVIDIA-blessed package: https://github.com/mosaicml/llm-foundry/issues/154

**Comment by mvpatel2000** [comment]
We're going to be deprecating healthchecker, which will remove `pynvml` entirely. I've opened the deprecation PR [here](https://github.com/mosaicml/composer/pull/2236). Closing this issue accordingly.
