### ISSUE TITLE
can Trainer support multiple train_dataloader?

### ISSUE THREAD

**Issue by BoyuanJiang** [mosaicml/composer#2304]
## 🚀 Feature Request
support multiple dataloader for trainer

## Motivation

For example, I have three aspect ratio images, 1:1,4:3 and 3:4, I wonder whether trainer can accept three dataloader, so when I train my model, the batch 1 receive data from dataloader1, so all images have 1:1 aspect ratio, batch 2 receive data from dataloader2 and all images have 4:3 aspect ratio, batch 3 receive data from dataloader3 and all images have 3:4 aspect ratio, batch 4 receive data from dataloader1 again?

**Comment by mvpatel2000** [comment]
Unfortunately, we do not provide this functionality at this time. Instead, we recommend creating a parent iterable that has 3 dataloader attributes and iteratively polls from them.

Alternatively, if you are using our `Streaming` datasets, you can pass in different `Stream`s for each resolution into your `StreamingDataset` class, and it will provide the functionality you are looking for. This is what we typically recommend. See docs [here](https://docs.mosaicml.com/projects/streaming/en/stable/api_reference/generated/streaming.Stream.html#streaming.Stream).

**Comment by BoyuanJiang** [comment]
yes I use Streaming datasets, suppose I have passed three different stream to Streaming dataset, each stream have a different resolution. How can ensure in every batch each rank get data from the same stream so they have the same resolution?

**Comment by BoyuanJiang** [comment]
> Unfortunately, we do not provide this functionality at this time. Instead, we recommend creating a parent iterable that has 3 dataloader attributes and iteratively polls from them.
> 
> Alternatively, if you are using our `Streaming` datasets, you can pass in different `Stream`s for each resolution into your `StreamingDataset` class, and it will provide the functionality you are looking for. This is what we typically recommend. See docs [here](https://docs.mosaicml.com/projects/streaming/en/stable/api_reference/generated/streaming.Stream.html#streaming.Stream).

yes I use Streaming datasets, suppose I have passed three different stream to Streaming dataset, each stream have a different resolution. How can ensure in every batch each rank get data from the same stream so they have the same resolution?

**Comment by karan6181** [comment]
Hi @BoyuanJiang , streaming dataset under the hood manages the samples in such a way that each batch comes from one Stream, so in your case, all the samples in each batch will contains same resolution.

**Comment by BoyuanJiang** [comment]
Hi @karan6181, what should I do when initializing the streaming dataset? Now I use the code from [here](https://github.com/mosaicml/diffusion/blob/main/diffusion/datasets/laion/laion.py#L162), but I found in a batch sample may from different mds files so they have different resolution.

**Comment by BoyuanJiang** [comment]
> Hi @karan6181, what should I do when initializing the streaming dataset? Now I use the code from [here](https://github.com/mosaicml/diffusion/blob/main/diffusion/datasets/laion/laion.py#L162), but I found in a batch sample may from different mds files so they have different resolution.

@mvpatel2000 @karan6181 any suggestion about this? I still don't know how to get data from one stream in each batch when I initialize streamdataset with multiple streams.
