### ISSUE TITLE
Print checkpointing info

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#234]
## 🚀 Feature Request
Currently the checkpointing functionality appears to be entirely silent when successful, both for saving and loading. There is [code](https://github.com/mosaicml/composer/blob/8580dfbf7ea27371098e27c8552659b84ef792f8/composer/trainer/checkpoint.py#L313) to print information about checkpoint saving, so it's silence may be a log level issue. Checkpoint loading should at least indicate success, and probably print information about the model params and hparams that were loaded.

**Comment by ravi-mosaicml** [comment]
You're right, the default loglevel to print is warning. I think it could make sense to change this to info:
https://github.com/mosaicml/composer/blob/357181dfa2e6bf51605134c10c44a026563f27c1/composer/trainer/trainer_hparams.py#L200

Could you send a PR over to 1) add what would be an appropriate amount of logging for checkpoint loading (note that there are already TQDM bars if you're downloading a checkpoint from cloud storage), and 2) change the default loglevel to INFO? Thanks!
