### ISSUE TITLE
Multiple optimizers support?

### ISSUE THREAD

**Issue by BoyuanJiang** [mosaicml/composer#2361]
## 🚀 Feature Request

I wonder whether support multiple optimizers so can use to train GAN?

**Comment by dakinggg** [comment]
We don't have direct support for this on our roadmap.

You may be able to create a custom optimizer class that just wraps your optimizers. You can overload the step() method and just make sure the corresponding optimizer steps are called in the correct order.
As a reference, this is very similar to what we do for SAM:
https://github.com/mosaicml/composer/blob/v0.14.1/composer/algorithms/sam/sam.py
