### ISSUE TITLE
Autoresume not working with wandb logger 

### ISSUE THREAD

**Issue by seyuboglu** [mosaicml/composer#2365]
** Environment **
Collecting system information...
---------------------------------
System Environment Report        
Created: 2023-07-13 23:23:53 UTC
---------------------------------

PyTorch information
-------------------
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.176+-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB

Nvidia driver version: 470.182.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.13.1+cu117
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==0.11.3
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1+cu117
[conda] Could not collect

Composer information
--------------------
Composer version: 0.14.1
Composer commit hash: None
Host processor model name: Intel(R) Xeon(R) CPU @ 2.20GHz
Host processor core count: 24
Number of nodes: 1
Accelerator model name: NVIDIA A100-SXM4-80GB
Accelerators per node: 1
CUDA Device Count: 4

** To reproduce

1. Setup a WandB Logger
2. Start a fresh run with autoresume=True

This leads to: 
wandb.errors.CommError: Unable to fetch artifact with name ... 

This occurs in `trainer.py` on 1396, when looping over the loggers to check if they have the latest checkpoint. Presumably this is because you are only catching filenotfound and notimplemented. 

## Expected behavior
"When the Trainer is configured with autoresume=True, it will automatically look for existing checkpoints and resume training. If no checkpoints exist, it’ll start a new training run. This allows you to automatically resume from any faults, with no code changes."

**Comment by mvpatel2000** [comment]
Can you please try upgrading to 0.15.1? The last patch release should fix this. I'm going to close for now, but feel free to reopen if you still hit issues
