### ISSUE TITLE
Timer interval helpers

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#241]
It would be really nice if we could do something like this:

```python3
def on_batch_end(self):
    if state.timer % Time.from_timestring("10 samples") == 0:
        pass  # do something every 10 samples
```

The issue with the above code is the timer could skip over sample counts that divisible by 10 -- e.g. if the batch size is 6, it would jump from 6 to 12 to 18 to 24 to 30, etc..., and the trigger would occur once every 30 samples -- not 10. Instead, it would be nice if the tigger could happen at the first timestamp at or after the interval -- e.g. sample 12, sample 24, and sample 30 (but not sample 6 or 18).

I think this could be implemented through a helper class that takes a reference to the timer, along with the interval, and has an API like this:

```python3
def __init__(self):
  self.interval = TimerInterval(self.state,timer, interval=Time.from_timestring("10 samples"))

def on_batch_end(self):
    if self.interval.step():  # returns True if the step count is 12, 24, 30, 42, ...; otherwise False
       pass
```

Then, this helper can be used wherever we have an `interval` or `every_n` parameter (e.g. `log_interval` in the file logger; `interval` in SAM, `validate_every_n_epochs` in the trainer, `upload_every_n_batches` in the run directory uploader. This list is not exclusive). Specifically,

* All interval parameters should not assume a unit (like batches or epochs) and instead be called `interval` or the like
* If the interval appears in a getter or instance attribute, it should be of type `Time`. If it appears in a setter or public facing function (including `__init__`), it should have type `Union[Time, str]` (internally, it can be converted to `Time` via `Time.from_timestring(interval)`. If it appears in the hparams, it should be of type `str`, but the `initialize_object` function should convert it to `Time` via `Time.from_timestring(interval)`.
* All interval checks should use this helper class (Hint: grep for `%` in `.py` files!)

**Comment by Bearnardd** [comment]
Hi @ravi-mosaicml! Is this issue still valid? If so I would love to add this feature.

**Comment by mvpatel2000** [comment]
This is not on the roadmap  for now but we're open to community PRs :)
