### ISSUE TITLE
Upload more complex metrics / evaluations to WandB

### ISSUE THREAD

**Issue by jmif** [mosaicml/composer#2457]
## 🚀 Feature Request

I’d like to be able to upload different types of metrics and evaluations to WandB, specifically I’d like to upload a confusion matrix.

WandB [supports it](https://wandb.ai/wandb/plots/reports/Confusion-Matrix-Usage-and-Examples--VmlldzozMDg1NTM) by uploading the predictions and labels directly.  They also support [uploading tables](https://docs.wandb.ai/guides/track/log/log-tables) which can be associated with an artifact. 

It looks like the options to achieve this would be directly uploading eval predictions (preferred as we could use the native confusion matrix feature) or uploading a table and using the Torch metrics confusion matrix values.  

I’ve done some digging into the code base but I’m not seeing a way to reasonably do this.  From what I can tell loggers accept metrics in the form of a [dictionary mapping metric name to a float](https://github.com/mosaicml/composer/blob/8ceedfc09cba64584f9dcd09e4d015c55fcea759/composer/loggers/logger.py#L63) which doesn’t seem compatible with the torch metrics confusion matrix and I can’t find a way to get access to the actual eval predictions / labels via callbacks or logger events.

Happy to submit a PR if this is something that would be accepted but will need some guidance as to how to tackle as I’m still learning Composer!

**Comment by mvpatel2000** [comment]
> I can’t find a way to get access to the actual eval predictions / labels via callbacks or logger events.
You can look at `state.batch` and `state.outputs`

I believe the right solution is to create a custom callback which would compute whatever you would like. You can then iterate over `state.callbacks` to find the Wandb logger and then call the function you would like directly instead of through the logging API....

Let me know if that works! Happy to talk through other designs

**Comment by mvpatel2000** [comment]
@jmif I'm going to close this issue, but feel free to reopen if you hit issues
