### ISSUE TITLE
Ignore strict state_dict checking.

### ISSUE THREAD

**Issue by cinjon** [mosaicml/composer#2473]
## 🚀 Feature Request

I am trying to start from a pre-trained model and add stuff to the llm model in https://github.com/mosaicml/examples/tree/v0.0.4/examples/llm. However, the Composer loading process is getting flustered by the state_dict being difference. There doesn't seem to be a way to control for this, i.e. I want to turn off strict state_dict checking.

**Comment by eracah** [comment]
you might want to also check out `github.com/mosaicml/llm-foundry`

**Comment by cinjon** [comment]
Yep, helps. Thanks!
