### ISSUE TITLE
Replace custom composer ResNet with torchvision ResNet

### ISSUE THREAD

**Issue by Landanjs** [mosaicml/composer#260]
## 🚀 Feature Request

Replace the composer ResNet model with the torchvision ResNet model.

## Motivation

The composer ResNet model appears largely identical to the [torchvision ResNet model ](https://github.com/mosaicml/composer/blob/dev/composer/models/resnets.py). I think our benchmarks would be cleaner if we used the torchvision model instead of our custom ResNet since users will be more familiar with torchvision models. Also, other vision benchmarks like DeepLabV3 will use torchvision ResNet backbones, so it would be good to align our classification benchmark with the new vision benchmarks.

**Comment by hanlint** [comment]
Yes, this makes a lot of sense -- lets do it!
