### ISSUE TITLE
AttributeError on DeviceMPS

### ISSUE THREAD

**Issue by agathedvlp** [mosaicml/composer#2632]
** Environment **

PyTorch information
-------------------
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.6 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 (main, Sep  4 2023, 18:40:56) [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] mypy==1.5.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] pytorch-lightning==2.0.9.post0
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==1.0.3
[pip3] torchvision==0.15.2
[conda] Could not collect

Composer information
--------------------
Composer version: 0.16.3
Composer commit hash: None
Host processor model name: Apple M2 Pro
Host processor core count: 12
Number of nodes: 1
Accelerator model name: N/A
Accelerators per node: 0
CUDA Device Count: 0

## Context 
`self._eval_loop()` crashes line 2910 of train.py when `isinstance(self.state.device, DeviceMPS)` and `self.state.outputs` is a dictionary with error: `AttributeError: 'dict' object has no attribute 'cpu'` however manually setting the device to "cpu" runs without error.

## Expected behavior
We would expect to have the same behaviour regardless of the device.

**Comment by mvpatel2000** [comment]
Thanks for flagging this! We will have a fix soon :)

**Comment by mvpatel2000** [comment]
https://github.com/mosaicml/composer/pull/2706 Should be fixed! Please let me know if you hit any errors
