### ISSUE TITLE
CUDA error: initialization error during distributed training when num_workers > 0 in eval_dataloader and metrics are not None

### ISSUE THREAD

**Issue by anastasia-spb** [mosaicml/composer#2673]
** Environment **

PyTorch information
-------------------
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.3
Libc version: glibc-2.31

Python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY

Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-pfn-extras==0.7.2
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1+cu118
[pip3] torch-optimizer==0.3.0
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.0.3
[pip3] torchtext==0.15.2+cpu
[pip3] torchvision==0.15.2+cu118
[conda] Could not collect

Composer information
--------------------
Composer version: 0.16.4
Composer commit hash: None
Host processor model name: Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz
Host processor core count: 14
Number of nodes: 1
Accelerator model name: NVIDIA GeForce RTX 2080 Ti
Accelerators per node: 1
CUDA Device Count: 4

Used dockerimage:  mosaicml/pytorch_vision:2.0.1_cu118-python3.10-ubuntu20.04

** To reproduce

1. Create train and eval data loaders with num_workers > 0
2.  Add metric  from torchmetrics import Metric, e.g.:
```
import torch
from torchmetrics import Metric
from torchmetrics.classification import BinaryJaccardIndex

class JaccardMetric(Metric):
    """Turns any torch.nn Loss Module into distributed torchmetrics Metric."""

    def __init__(self, threshold=0.5, dist_sync_on_step=True):
        super().__init__(dist_sync_on_step=dist_sync_on_step)
        self.metric = BinaryJaccardIndex(threshold=threshold)
        self.add_state("jaccard_mean", default=torch.tensor(0.), dist_reduce_fx="sum")
        self.add_state("total_batches", default=torch.tensor(0), dist_reduce_fx="sum")

    def update(self, preds, target):
        """Update the state with new predictions and targets.
        """
        self.jaccard_mean += self.metric(preds, target)
        self.total_batches += 1

    def compute(self):
        """Aggregate state over all processes and compute the metric.
        """
        # Return average loss over entire validation dataset
        return self.jaccard_mean / self.total_batches
```
3. Launch train on multiple gpu, e.g.: composer -n 2 train.py

Script fails with 
```
terminate called after throwing an instance of 'c10::Error' 0/40 [00:00<?, ?ba/s]                                                                  
what():  CUDA error: initialization error
```
after first train epoch

Similar issue: https://github.com/Lightning-AI/torchmetrics/issues/1560

## Expected behavior

Script shall not fail when metrics calculation is called.

## Additional

Execution is successful if num_workers is 0 or if metrics are None or train on single GPU

**Comment by mvpatel2000** [comment]
C10 errors are typically torch related. I'm going to close this because I think this is a torch issue -- please let me know if you find anything else though!
