### ISSUE TITLE
`speed_monitor` incorrectly divides throughput by `grad_accum`

### ISSUE THREAD

**Issue by dblalock** [mosaicml/composer#271]
## Environment
Internal cluster, internal pytorch image, `dev branch`

## To reproduce

Working launch config posted in slack. Launching any two runs differing only in `grad_accum` should work.

## Expected behavior

Reported throughput should weakly depend on `grad_accum`. Instead, it's inversely proportional to `grad_accum`.

## Additional context

Seems to be a result of `speed_monitor.batch_end` using `state.batch_num_samples` as its batch size. The implementation in `trainer._train_batch_inner` actually sets this value to the *microbatch* size at the start of each microbatch. The structure is roughly this:
```
trainer._train_loop
        run event.batch_start
        for microbatch in batch:
            state.batch_num_samples = len(microbatch)
            ...
        run event.batch_end // speed_monitor snapshots state.batch_num_samples here
```
Not sure what the right solution is, which is why this is an issue rather than a quick PR to fix it.

[WandB results](https://wandb.ai/mosaic-ml/thruput-bug?workspace=user-dblalock) from above reproduction. Also saw the same behavior with ResNet-50 using 8 gpus, so confident that this is not tied to GPU count.

**Comment by ravirahman** [comment]
I think https://github.com/mosaicml/composer/issues/265 will also address this issue. For now, would it work to read the batch sizing on `Event.AFTER_DATALOADER`, store it on `self.`, and read it on the batch end event?

**Comment by dblalock** [comment]
That would probably work. I'm personally fine just waiting for the real fix though; mostly just wanted to make sure we capture this behavior / no one else goes down a rabbit hole trying to figure out why their throughputs are weird.
