### ISSUE TITLE
HuggingFace Pre-trained model Fine Tuning Error

### ISSUE THREAD

**Issue by jaintarunAI** [mosaicml/composer#2720]
I am following this tutorial:[Pre-Train Fine Tuning](https://docs.mosaicml.com/projects/composer/en/stable/examples/pretrain_finetune_huggingface.html)

- I tried Ag_news dataset with Llama-7B model using A100 GPU - 40 GB
- I also tried the same dataset with orca-mini-3b using A100 GPU - 40 GB 

Both the times, I got OutOfMemoryError: CUDA out of memory. Later I took a smaller dataset of 500 rows and still facing the same error - OutOfMemoryError. 

![Screenshot from 2023-11-16 14-28-38](https://github.com/mosaicml/composer/assets/132284203/378bd0b5-26a1-4dee-a70e-781287037c48)

>
> # Can anyone please help me out!
>

Here are the two different approach I took to define the Trainer:

- Using FP32

```py
trainer = Trainer(
    model=composer_model, # This is the model from the HuggingFaceModel wrapper class.
    train_dataloader=train_dataloader,
    eval_dataloader=eval_dataloader,
    max_duration='1ep', # train for more epochs to get better performance
    save_folder='checkpoints/pretraining/',
    optimizers=optimizer,
    schedulers=[lr_scheduler],
    device='gpu' if torch.cuda.is_available() else 'cpu',
    # train_subset_num_batches=100, # uncomment this line to only run part of training, which will be faster
    precision='amp_fp16',
    seed=17,
)
```

- Using AMP16 with single batch size (1ba)

```py
trainer = Trainer(
    model=composer_model, # This is the model from the HuggingFaceModel wrapper class.
    train_dataloader=train_dataloader,
    eval_dataloader=eval_dataloader,
    max_duration='1ep', # train for more epochs to get better performance
    save_folder='checkpoints/pretraining/',
    optimizers=optimizer,
    schedulers=[lr_scheduler],
    device='gpu' if torch.cuda.is_available() else 'cpu',
    train_subset_num_batches=100, # uncomment this line to only run part of training, which will be faster
    precision='amp_fp16',
    deepspeed_config={
        "train_batch_size": 1,
        "fp16": {"enabled": True},
}
)
```

**Comment by jaintarunAI** [comment]
![Screenshot from 2023-11-16 14-39-46](https://github.com/mosaicml/composer/assets/132284203/c98295fc-104c-487f-888e-39c53ff096db)

**Comment by mvpatel2000** [comment]
@jaintarunAI Composer supports microbatching to avoid ooms. You can specify `device_train_microbatch_size=1` to use miniaml memory (ideally it is as large as possibe while fitting). The same can be done on evaluators with `device_eval_microbatch_size`. We also support `device_train_microbatch_size='auto'`, though it may not always work.
