### ISSUE TITLE
Remove usage of `hparams` objects internally

### ISSUE THREAD

**Issue by hanlint** [mosaicml/composer#279]
As part of deYAHPification, we should remove the use of `hparams` internally within the code. For example, previously in algorithms we had:
```
class MyAlgorithm:
    def __init__(alpha=0.1, beta=0.2):
        self.hparams = MyAlgorithmHparams(alpha=alpha, beta=beta)
```

but we prefer:
```
class MyAlgorithm:
    def __init__(alpha=0.1, beta=0.2):
        self.alpha = alpha
        self.beta = beta
```

This disentangles the core logic from YAHP, as noted in #194 . #269 may already have designs to do this (cc: @jbloxham ), but if we not we can plan this work separately.

**Comment by jbloxham** [comment]
Closed by #317
