### ISSUE TITLE
WandBLogger init is a hot mess

### ISSUE THREAD

**Issue by seanbethard** [mosaicml/composer#2809]
Why do only some wandb init args work?

`wandb_logger = WandBLogger(project="project-name")`

wandb keyword arg is fine.

`wandb_logger = WandBLogger(project="project-name", notes="note")`

wandb keyword arg is not fine.

`TypeError: WandBLogger.__init__() got an unexpected keyword argument 'notes'`

https://docs.wandb.ai/ref/python/init

**Comment by hanlint** [comment]
Hello @seanbethard, thanks for raising this issue. 

Our `WandBLogger` supports all the wandb args via the `init_kwargs` method. A few common ones, we also support for convenience, as accepted by the `__init__`. 

So, in your example, you can do:
```
wandb_logger = WandBLogger(project='project-name', init_kwargs=dict(notes="note", ...))
```

For more details, please see: https://docs.mosaicml.com/projects/composer/en/stable/api_reference/generated/composer.loggers.WandBLogger.html

**Comment by seanbethard** [comment]
Thanks for clarifying. The `wandb` docs reference an `init_params` arg which appears to be deprecated so it took some poking around to figure out what worked. It seems that each integration has its own way of setting up `init` so maybe some poking around is expected. Since it was a design choice to make only some common args directly available to the constructor it looks like there's nothing to do here.
