### ISSUE TITLE
ResNet56 default num_classes argument

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#286]
## 🚀 Feature Request
The `num_classes` argument for [ResNet56_cifar10](https://github.com/mosaicml/composer/blob/main/composer/models/resnet56_cifar10/model.py) should have a default value `num_classes=10`.

## Motivation

It felt silly when writing a demo notebook to have to specify `num_classes=10` when calling `composer.models.CIFAR10_ResNet56(num_classes=10)`. The model has "cifar10" in its name, and even if it didn't, it's most common use is for cifar10.

## Implementation

Does it require any changes beyond the `__init__()` signature?

**Comment by growlix** [comment]
Soliciting @A-Jacobson @hanlint @coryMosaicML for thoughts

**Comment by hanlint** [comment]
Yeah, this should be an easy one-liner.
