### ISSUE TITLE
`0.18.1` not available in PyPI

### ISSUE THREAD

**Issue by antoinebrl** [mosaicml/composer#2936]
I see on GitHub that `0.18.1` was released 5 days ago with the corresponding changelog. However, this version of `composer` is not available in PyPI (https://pypi.org/project/composer/#history). What the release process completed successfully?

**Comment by mvpatel2000** [comment]
We're having some issues with the release process -- it should be out soon! @b-chu will have an update once its out

**Comment by antoinebrl** [comment]
Thanks for the update and good luck!

**Comment by b-chu** [comment]
It's up on PyPi now!
