### ISSUE TITLE
Add support for Pytorch 2.2.0

### ISSUE THREAD

**Issue by jnfinitym** [mosaicml/composer#2943]
## 🚀 Feature Request
Version 0.18.1 is currently not compatible with the current stable version of PyTorch 2.2.0. I suggest to add compatibility in the next release version

## Motivation

It would be nice to easily take advantage of new features, such as FlashAttention 2

## [Optional] Implementation

I haven't looked into compatibility yet (So I am not sure if there is anything the new version breaks), but I am happy to test and potentially fix and then contribute this in a pull request if needed.

**Comment by mvpatel2000** [comment]
@jnfinitym We've merged it into dev https://github.com/mosaicml/composer/pull/2933! It'll go out in a release we plan to do this week.
