### ISSUE TITLE
TQDM spams lines during validation when running trainer.fit() in notebook

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#295]
** Environment **
Colab notebook.

<img width="607" alt="TQDM Spam" src="https://user-images.githubusercontent.com/11728034/151625792-31dc2c0e-d572-43d1-9514-5127a6a3751b.png">

** To reproduce

run `trainer.fit()` in a Colab notebook. See [this notebook](https://colab.research.google.com/drive/12Dl0NVDaj4tf4gfpfg-rkIAoO_H7edo3?usp=sharing) for an example.

## Expected behavior

TQDM output should remain on a single line during evaluation, which happens during training.

**Comment by hanlint** [comment]
I think the solution here is for `composer` to import from `tqdm.notebook import tqdm` based on a trainer arg

**Comment by moinnadeem** [comment]
I think TQDM can actually autodetect whether to run in a notebook or console environment if we use `from tqdm.autonotebook import tqdm`
