### ISSUE TITLE
`surgery.replace_module_classes` should copy initialization weights where possible

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#297]
## 🚀 Feature Request

Right now, `surgery.replace_module_classes` does not preserve any initialized model weights for modules that are replaced. However, in cases where there is a 1-1 mapping of weights in the replacement (ex. in StoachasticDepth), we should preserve initialized model weights. 

## Motivation

Surfaced by a user.

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri
