### ISSUE TITLE
Surgery and StochasticDepth Doc Updates

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#300]
- `surgery.replace_module_classes` docs should explicitly state that model weights are not copied over. Once #297 is implemented the statement can be amended to include that model weights are copied over in the case of a 1-1 mapping
-  Until #253 is implemented, `StochasticDepth` docs need to explicitly state that it only works on Composer's ResNet model.

**Comment by hanlint** [comment]
As #297 is not in `v0.4`, moving this out of `v0.4`. We'll be sure to add documentation to StochasticDepth around the models it supports.

**Comment by ajaysaini725** [comment]
Addressed by #413
