### ISSUE TITLE
Documentation on independence of algorithm realizations across GPUs

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#301]
Currently when a seed is passed into the trainer the following occurs:

```
seed += dist.get_global_rank()
reproducibility.seed_all(seed)
self.seed = seed
```

This means that each process uses a different (but deterministic) seed. This has two implications:

1. Stochastic algorithms that are applied individually in a process/gpu are independent realizations. For example, the image patches that are cut out by CutOut will be independently sampled (and likely different) on each GPU.

2. Results will change depending on the number of processes/devices used during training.

Having different seeds (and hence independent sampling) for different GPUs is desirable because it increases the diversity of data generated by stochastic transformations. However, this affects replicability, and users should be very aware of this behavior. The documentation of all affected methods should be updated to make this very clear. There are also probably other places where we want to mention this.

cc @ajaysaini725 @hanlint @coryMosaicML @jbloxham

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri
