### ISSUE TITLE
Automatically Validate Docstrings

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#307]
1. After changing batches -> iterations, we have some significantly out-of-date documentation. Let's grep over this all over the codebase and figure out what we need to update

**Comment by dblalock** [comment]
Personally I'd vote for just having type annotations in the function signature, which sphinx auto-generates. So (3) wouldn't fail anything. But this decision might have already been made, so ignore me if it has.

**Comment by ravi-mosaicml** [comment]
Going to use this issue to track automatic docstring validation. Any broken docstrings should either be fixed via PRs or have issues created for them -- it's too broad as written.
