### ISSUE TITLE
Update packaging from <23 to <24

### ISSUE THREAD

**Issue by Ryu1845** [mosaicml/composer#3071]
## 🚀 Feature Request

Upgrade packaging from <23 to <24
## Motivation

I depend on a package requiring packaging>=23 (deepfilternet) which is in direct contradiction of this project, so I can't install both at the same time.

**Comment by mvpatel2000** [comment]
https://github.com/mosaicml/composer/pull/3072

Bumped in dev! It will go out in release next week.
