### ISSUE TITLE
Composer -V

### ISSUE THREAD

**Issue by Averylamp** [mosaicml/composer#309]
## 🚀 Feature Request
Composer launch script also with `composer --version/-V` arg to printout composer version.
## Motivation
Helpful for automated scripts

**Comment by hanlint** [comment]
We currently use `-v/--verbose` to control the logging verbosity. Is there something else we should use / what is the standard here?

**Comment by ravi-mosaicml** [comment]
After #315 is merged in, this should work:

```bash
python -c "import composer; print(composer.__version__)"
```

Would prefer to wait on adding in `-v`/`--version` for now since having `.__version__` is the standard python way to include the version number (and the launch script is specifically for distributed training, not composer in general).

**Comment by Averylamp** [comment]
My mistake, version is usually uppercase V.  
I think its useful for entrypoint/cli tools to always have the version tagged into it, even if it does the `composer.__version__` in its own way.  Another request for verbosity is setting verbosity levels versus just a flag.  if -v is used, often its `-v` `-vv` `-vvv` for different verbosity levels.

**Comment by ravi-mosaicml** [comment]
Doing the cli will require some refactoring to make a new entrypoint, where the current launcher script is a subcommand within it. E.g. wandb does this:

```
(composer) ravi@dolphin:~/composer$ wandb --help
Usage: wandb [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  agent         Run the W&B agent
  artifact      Commands for interacting with artifacts
  controller    Run the W&B local sweep controller
  disabled      Disable W&B.
  docker        W&B docker lets you run your code in a docker image...
  docker-run    Simple wrapper for `docker run` which adds WANDB_API_KEY...
  enabled       Enable W&B.
  init          Configure a directory with Weights & Biases
  launch        Launch or queue a job from a uri (Experimental).
  launch-agent  Run a W&B launch agent (Experimental)
  local         Launch local W&B container (Experimental)
  login         Login to Weights & Biases
  offline       Disable W&B sync
  online        Enable W&B sync
  pull          Pull files from Weights & Biases
  restore       Restore code, config and docker state for a run
  status        Show configuration settings
  sweep         Create a sweep
  sync          Upload an offline training directory to W&B
  verify        Verify your local instance
```

Going to defer this to v0.5, for now please use https://github.com/mosaicml/composer/issues/309#issuecomment-1026283704
