### ISSUE TITLE
The `Profiler` should upload generated traces to the logger.

### ISSUE THREAD

**Issue by antoinebrl** [mosaicml/composer#3114]
## 🚀 Feature Request
 The `Profiler` should push the generated files to the `logger`.

## Motivation

The `OOMObserver` is already pushing the produced files. Not all experiment tracking systems can display the traces from the profiler but having them managed just like any other experimentation artifact can be useful.

## Implementation

Unfortunately I don't have the bandwidth to look into implementing the upload.

**Comment by mvpatel2000** [comment]
This is a good suggestion :) We have a centralized logging solution, and we should leverage it. @cli99 curious for thoughts?

**Comment by mvpatel2000** [comment]
@antoinebrl  hmm actually can you elaborate a bit more please? I see we already do this:
https://github.com/mosaicml/composer/blob/dev/composer/profiler/torch_profiler.py#L289-L293

**Comment by antoinebrl** [comment]
Thanks for pointing to the exact line. I didn't realized this was exposed through the `Profiler` but with different parameter namas (`torch_prof_remote_file_name` and `torch_prof_memory_remote_file_name`)
