### ISSUE TITLE
override serialized fields when resuming from checkpoint

### ISSUE THREAD

**Issue by stillmatic** [mosaicml/composer#3154]
## 🚀 Feature Request

I would like the ability to override certain serialized fields (specifically, scheduler state) when resuming from a checkpoint.

## Motivation

A common strategy to deal with model loss not decreasing is to lower learning rate. 

![image](https://github.com/mosaicml/composer/assets/4743676/99b79826-2fa6-44ae-bac7-aad218dbc8d5)

For example, the FB [OPT paper](https://arxiv.org/pdf/2205.01068.pdf) showed that they had to manually lower learning rate many times to keep the run stable/learning. There are probably better ways to do this (pick a better LR or scheduler) but sometimes you regret your decisions and have to fix things as you can.

Composer currently reloads scheduler from checkpoint and doesn't respect changes to LR / scheduler as a result. Resuming from a checkpoint with lower learning rate just ignores the argument and restarts from the stored scheduler/LR.

**Comment by mvpatel2000** [comment]
Check out `load_ignore_keys`. You can filter the LR scheduler and it won't override on load
