### ISSUE TITLE
Allow default credentials for accessing GCS

### ISSUE THREAD

**Issue by aadyotb** [mosaicml/composer#3169]
## 🚀 Feature Request

Before throwing an exception, `GCSObjectStore` should attempt to use default GCP credentials if `GOOGLE_APPLICATION_CREDENTIALS`, `GCS_SECRET`, and/or `GCS_KEY` are not defined as environment variables. If this also fails, then the exception should be thrown.

## Motivation

When I attempt to use the `composer` library on a GCP node which is authenticated to access my private GCS via the service account it is running, I encounter an exception due to the aforementioned environment variables being unset. I've made a local modification (below) that simply creates the default GCS client to connect to the specified bucket; this works because my service account information is already set up how GCP expects it to be. I would like the code to check the default credentials before throwing an exception.

## [Optional] Implementation

I've made a modified version of the class to work for my personal use cases:

```
class GCSObjectStore(composer.utils.object_store.GCSObjectStore):
    def __init__(self, bucket: str, prefix: str = ""):
        try:
            super().__init__(bucket=bucket, prefix=prefix)
        except ValueError as e:
            if "GOOGLE_APPLICATION_CREDENTIALS" in str(e):
                self.client = google.cloud.storage.Client()
                self.bucket = self.client.get_bucket(self.bucket_name, timeout=60)
                self.use_gcs_sdk = True
            else:
                raise e
```

**Comment by aadyotb** [comment]
To be clear, would your suggested change (based on `_gcs_with_service_account` in that file)  be to replace `self.client = google.cloud.storage.Client()` with the following?
```
credentials, _ = default_auth()
Client(credentials=credentials)
```

**Comment by karan6181** [comment]
@aadyotb Sorry for my late response. 

> To be clear, would your suggested change (based on _gcs_with_service_account in that file) be to replace self.client = google.cloud.storage.Client() with the following?

Yes.

[Here](https://github.com/mosaicml/streaming/pull/376) is the Streaming Dataset PR for your reference.

**Comment by aadyotb** [comment]
@karan6181 that change works!
