### ISSUE TITLE
Use GPUs in tests

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#32]
## 🚀 Feature Request

We have a number of unit tests (ex. `tests/trainer/test_trainer.py` and `tests/trainer/test_checkpoint.py` which use GPUs as a part of the test. However, these tests are not run as a part of the GitHub actions tests, which results in the potential for GPU-related bugs. We should have a system in place which runs GPU tests before code can be merged into `dev`.

## Motivation

There have been GPU-specific bugs in the past that were not caught because GPU tests do not run in our unit testing suite.

## Implementation

Can use CircleCI for this.

**Comment by ravi-mosaicml** [comment]
#82 will include GPU tests
