### ISSUE TITLE
Merge `LanguageCrossEntropyLoss` and `CrossEntropyLoss` metrics

### ISSUE THREAD

**Issue by Landanjs** [mosaicml/composer#323]
`LanguageCrossEntropyLoss` metric accepts both a mapping and tensor in `update()`, but the remaining functionality appears the same as `CrossEntropyLoss`. These metrics should be combined to reduce redundant code.

**Comment by moinnadeem** [comment]
😬 Sorry for this, it's my code!

I can try to work on this soon -- but feel free to take a stab at it if I don't get it in time

**Comment by mvpatel2000** [comment]
Closing as done
