### ISSUE TITLE
Unify time arguments for SchedulerHparams and Scheduler objects

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#324]
## 🚀 Feature Request
Currently, duration (e.g. `warmup_iters` or `T_max`) and resolution (steps or epochs) are fully dissociated for SchedulerHparams, and duration is specified as a string, and the magical `composer.Time` handles the time conversions under the hood. PR #249 moved us away from using `*Hparam` objects and towards using Scheduler/Optimizer objects, but unfortunately the Scheduler objects don't use `Time` under the hood for duration, nor do they dissociate update resolution from duration. It would be great if they did.

## Motivation

1. Composer's `Time` handling is magical
2. Duration and resolution of LR schedules should be dissociated
3. We should try to keep the interfaces for `*Hparams` their associated objects consistent.

## [Optional] Implementation

Looks like a lot of Schedulers are pulling from pytorch directly, so I'm not sure what the cleanest way to do this is, but if someone wants to point me in the right direction I'm happy to do it.

Thoughts @hanlint, @ravi-mosaicml, @jbloxham

**Comment by jbloxham** [comment]
Can you elaborate on what the dissociation of duration and resolution should look like?

**Comment by growlix** [comment]
For example, you can instantiate a `WarmUpLRHparams` object like:
```
warmup = composer.optim.WarmUpLRHparams(
    warmup_iters="2ep", # Warmup duration
    warmup_method="linear", # Linear warmup
    warmup_factor=1e-4, # Initial LR = LR * warmup_factor
    interval="step" # Update LR with stepwise resolution for superior results
)

**Comment by hanlint** [comment]
Based on discussions in #259 , I think we want to redo how we treat schedulers entirely. This would involve:
* Removing `ComposerScheduler`
* Implementing some common schedulers as `LambdaLR` stateless schedulers (e.g. `warmup_with_cosine_decay`)
