### ISSUE TITLE
TORCH_NCCL_ASYNC_ERROR_HANDLING vs NCCL_ASYNC_ERROR_HANDLING at launcher.py

### ISSUE THREAD

**Issue by priba** [mosaicml/composer#3266]
I've got some warnings about using `NCCL_ASYNC_ERROR_HANDLING` instead of `TORCH_NCCL_ASYNC_ERROR_HANDLING`. See:

```
[rank0]:[W Utils.hpp:108] Warning: Environment variable NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
```

Shall we update the `launcher.py` to use this variable? 

https://github.com/mosaicml/composer/blob/9f7db040bb71b108cb5552189997b476f1c20979/composer/cli/launcher.py#L342

As far as I know, `TORCH_NCCL_ASYNC_ERROR_HANDLING` is more specific for the Pytorch use case. Is there any reason to keep `NCCL_ASYNC_ERROR_HANDLING`?

I am happy to submit a PR with this change.

**Comment by mvpatel2000** [comment]
Ah, that seems like a good fix! If you can submit a PR, that would be great. It would be good to ensure the new environment variable also works in the oldest pytorch version we support (torch 2.1)

**Comment by priba** [comment]
@mvpatel2000 I've marked the PR as WIP as I don't see that the CI runs GPU tests on different pytorch versions. It seems that just runs [gpu-3.11-2.3](https://github.com/mosaicml/composer/actions/runs/9006577490/job/24744422304#logs).

Shall we add different pytorch versions in the test matrix?

Do you have any suggestion on how to properly test that the new environment variable also works in the oldest pytorch version?

**Comment by mvpatel2000** [comment]
> @mvpatel2000 I've marked the PR as WIP as I don't see that the CI runs GPU tests on different pytorch versions. It seems that just runs [gpu-3.11-2.3](https://github.com/mosaicml/composer/actions/runs/9006577490/job/24744422304#logs).

GPU daily tests run on all versions but not on PR!

> Do you have any suggestion on how to properly test that the new environment variable also works in the oldest pytorch version?

I ran manual tests in an interactive instance! Merged since it looks good :)
