### ISSUE TITLE
Ensure that the INIT event is idempotent

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#327]
As we implement #138 and #40, the init event be called multiple times, potentially in the same training run. As such, it will need to be idempotent wherever it is used. #328 implements this.

**Comment by dblalock** [comment]
Does this include algorithms that currently run on Event.INIT being idempotent? Because some of them will be but right now we have no tests or explicit support for that.

**Comment by ravi-mosaicml** [comment]
Yup, #328 fixes these algorithms and adds a (functional) test

**Comment by ravi-mosaicml** [comment]
Closed in #328
