### ISSUE TITLE
NUMA affinity control

### ISSUE THREAD

**Issue by gfiameni** [mosaicml/composer#3274]
Hi all,
is there a way to control CPU/GPU affinity through using composer? I would like to mimic `mpirun` `--map-by` and `--bind-to` options or, at least, get a bindings report to check that affinity is correct.

Thanks!

**Comment by bandish-shah** [comment]
Hi @gfiameni  thanks for the question! We don't have any NUMA hooks directly built into Composer or the distributed launcher. However you should be able to use `numactl` to bind processes to NUMA nodes or physical cores. I recommend taking a look at the following section in PyTorch's performance optimization guide:
https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#utilize-non-uniform-memory-access-numa-controls

**Comment by bandish-shah** [comment]
Closing this out, please feel free to reopen or create another issue if there is anything additional to discuss!
