### ISSUE TITLE
Training stops after first pass of Evaluation when pretraining MosaicBert

### ISSUE THREAD

**Issue by amishparekh** [mosaicml/composer#3421]
** Environment **
composer = 0.23.3, composer = 0.17.2
GPU Stack: 8 x A100 80GB
CUDA: 12.1

** To reproduce

1. Run MosaicBERT using https://github.com/Skylion007/mosaicml-examples/tree/skylion007/add-fa2-to-bert which has Flash Attention 2 implementation.
2. Change the remote data location to aws S3 path
3. Wait till the end of evaluation and observe GPU utilisation

## Expected behavior

Ideally, when running the script, the training starts and after every 2000 steps evaluation is performed post which training should resume

## Additional context

I ran the benchmark mosaicbert pretraining script and since we are having the data at a remote S3 location. I transferred the converted streaming dataset c4 to S3 bucket to test before running it on our data. The training started as expected and at 2000 steps the evaluation started, at the end of evaluation the GPU utilisation goes to zero and the training doesn't resume further.
I don't even see any error but my GPU memory is still occupied. Once I manually quit, GPU memory goes down and everything is back to normal. I am not able to figure out why the training doesn't resume or no error present. Since, the training started and evaluation reached till end as well, my guess is script may not be the issue and hence created a bug in composer if there is something I am missing.
Any help would be appreciated.
Thanks.

**Comment by jacobfulano** [comment]
Hi @amishparekh! Do I understand correctly that you run into this issue with both composer = 0.23.3 and composer = 0.17.2? What version of streaming are you using?

**Comment by amishparekh** [comment]
Hi @jacobfulano!
Yes I faced first with 0.17.2 so upgraded to 0.23.3. 
Here is my requirements file:
einops==0.5.0
torch==2.2.1
composer[nlp,wandb]==0.23.3
mosaicml-streaming==0.7
mosaicml==0.23.3
omegaconf==2.3.0
transformers==4.35.2
flash_attn==2.5.8
Thank you!

**Comment by amishparekh** [comment]
<img width="570" alt="Screenshot 2024-06-24 at 1 39 13 PM" src="https://github.com/mosaicml/composer/assets/120441303/5a2409fd-0c7a-4c2f-bf1d-a57b8cb3c5a6">
Wandb logging screenshot for reference.
<img width="1792" alt="Screenshot 2024-06-24 at 1 37 26 PM" src="https://github.com/mosaicml/composer/assets/120441303/32c0f8a1-3542-4dee-84b1-54fce0d5b09d">
Tried train_microbatch_size: auto, 128. Eval_batch_size: 128,64, 1.

**Comment by amishparekh** [comment]
Hi @jacobfulano!
Did you get a chance to look into this issue?
Any help will be massively appreciated. I see some issues for previous pytorch versions where num_workers>0 had some errors but I don't see how it will affect now.
Thanks

**Comment by mvpatel2000** [comment]
@Skylion007 as this is your branch/script, do you see this as well? if so, can you send a repro yaml? 

@amishparekh can you get raw logs before the broken pipe command? it looks like eval is still running from the print statements?

**Comment by amishparekh** [comment]
@mvpatel2000 Those were the raw logs, that is what was confusing to me as well. I found a small fix where I convert drop_last: true and the training resumes normally. Have not checked in depth why it worked.

**Comment by mvpatel2000** [comment]
Hm... ok it could be that different GPUs have different number of samples which causes a deadlock... if you have a repro I can investigate further

**Comment by amishparekh** [comment]
Okay. Closing the issue for now, since have it working for now.
Thanks @jacobfulano @mvpatel2000 @Skylion007 for looking into this.
