### ISSUE TITLE
How to use composer under python3.8

### ISSUE THREAD

**Issue by lqniunjunlper** [mosaicml/composer#3495]
** Environment **

** To reproduce
composer/utils/auto_log_hparams.py", line 13, in <module>
    def extract_hparams(locals_dict: dict[str, Any]) -> dict[str, Any]:
TypeError: 'type' object is not subscriptable

1.
2.
3.

**Comment by mvpatel2000** [comment]
See chip on [README](https://github.com/mosaicml/composer) 

<img width="791" alt="image" src="https://github.com/user-attachments/assets/899f615e-9345-4656-ae1f-201ad20e2e4e">

Composer supports a rolling list of 3 versions of python, which is currently Python 3.9-3.11. Accordingly, we recommend you upgrade.

You can also use an older release if you need Python 3.8.
