### ISSUE TITLE
Multi-TPU Training Support for Composer

### ISSUE THREAD

**Issue by Iambestfeed** [mosaicml/composer#3501]
## 🚀 Feature Request: Multi-TPU Training Support for Composer

Add native support for multi-TPU training workflows within the Composer library. This would enable efficient scaling of large language model training across multiple TPU pods (specifically targeting TPU v3-8 initially).

## Motivation

I'm often frustrated by the complexity of setting up multi-TPU training for large language models. While the MosaicML documentation provides guidance ([https://docs.mosaicml.com/projects/composer/en/stable/examples/TPU_Training_in_composer.html](https://docs.mosaicml.com/projects/composer/en/stable/examples/TPU_Training_in_composer.html)), integrating this into existing Composer workflows is not straightforward. 

Having built-in multi-TPU support within Composer would greatly simplify the process and make large-scale model training more accessible.

## [Optional] Implementation

* **Abstraction Layer:**  Create a new abstraction layer within Composer to handle multi-TPU communication and data parallelism.
* **Configuration:** Provide a simple configuration interface (e.g., YAML or Python-based) to specify the number of TPU devices, pod placement, and other relevant settings.
* **Integration with Algorithms:** Ensure seamless integration with existing Composer training algorithms and optimizers.
* **Example Scripts:** Include example scripts demonstrating how to train models like Mosaic BERT on multi-TPU setups.

## Additional context

* The primary use case is to facilitate the training of language models (like Mosaic BERT) on TPU v3-8 pods.
* The goal is to make multi-TPU training as simple and intuitive as single-device training within Composer.

**Comment by mvpatel2000** [comment]
We don't regularly use TPUs, so unfortunately the support is a bit worse. Can you highlight a few concrete pain points that need to be addressed? What exactly fails with the library as-is?

**Comment by Iambestfeed** [comment]
> We don't regularly use TPUs, so unfortunately the support is a bit worse. Can you highlight a few concrete pain points that need to be addressed? What exactly fails with the library as-is?

Hmmm, I saw your version using torch xla, but I'm curious if it is possible to use libraries for TPUs such as flax, jax. To be honest, I haven't experimented with them yet because I don't seem to really imagine where I should start. 

It seems a bit annoying but can you show me how to edit your framework?

**Comment by Iambestfeed** [comment]
> Composer is PyTorch built, so moving to JAX would be a big lift. You'd have to rewrite the distributed logic, which is a lot of effort. It's certainly possible to do both... but currently we are opinionated in requiring PyTorch

Hmm, thank you. 
It seems to me that with my current capabilities, switching a framework from torch to jax is still a complicated process. I will try again on another occasion.
