### ISSUE TITLE
"ValueError: Reused local directory" How should I reuse local file with streaming?

### ISSUE THREAD

**Issue by tayshinmit** [mosaicml/composer#3655]
However, I've encountered an issue when trying to reuse a dataset that's saved locally in MDS format. 

I keep getting the error: "ValueError: Reused local directory." How can I properly reuse the dataset? Is there a function to reinitialize the streaming process?

Thanks!

**Comment by mvpatel2000** [comment]
Can you open this in https://github.com/mosaicml/streaming instead please? It makes it easier for us to triage
