### ISSUE TITLE
[Question] Gradient Accumulation issue

### ISSUE THREAD

**Issue by mayankjobanputra** [mosaicml/composer#3680]
Based on my understanding of the current codebase (which can be wrong as well), I think composer never suffered from the "Gradient Accumulation problem". Is my understanding correct?

If I train BERT-like encoder model using composer, the Gradient Accumulation problem should not occur unlike in the earlier versions of Transformer trainer right?

**Comment by mayankjobanputra** [comment]
@mvpatel2000 Ah so sorry for not adding the problem reference but I was referring to this one: https://huggingface.co/blog/gradient_accumulation (original problem explained in the unsloth blog much better than this one.)

**Comment by mvpatel2000** [comment]
Flag I linked should provide correct implementation ("correct" being a bit subjective here) for that issue
