### ISSUE TITLE
Loosen `torchmetrics` requirements

### ISSUE THREAD

**Issue by antoinebrl** [mosaicml/composer#3690]
This [MR](https://github.com/mosaicml/composer/pull/3460) from dependabot reduced quite significantly the supported version of `torchmetrics` to '>=1.4.0.post0,<1.4.1'. I believe the goal was to bump the upper bound but not to increase the lower bound to a post release segment. Should this be set to something like  `torchmetrics>=1.0,<1.6`?

**Comment by mvpatel2000** [comment]
Good catch! Will be updated here: https://github.com/mosaicml/composer/pull/3691. Sorry about that
