### ISSUE TITLE
DistributedSampler seeding

### ISSUE THREAD

**Issue by janEbert** [mosaicml/composer#3723]
[The `DistributedSampler` is constructed with its default constant `seed=0` even when the `Trainer` is given a different seed.](https://github.com/mosaicml/composer/blob/b8cc29e27ddc3955fb445e5acd4a47ee444182cf/composer/utils/dist.py#L617-L623) (The sampler's `seed` attribute is also never set before its iteration, which would also work.) To me, this is unexpected, as I would expect the data distribution to also change when I change the global seed. As an alternative option to including the global seed when setting up the data sampler, it would be feasible to allow setting a separate `data_seed` with a default value of 0 (which would also preserve full backward compatibility).

** Environment **
Composer `main` (b8cc29e27ddc3955fb445e5acd4a47ee444182cf).

## Expected behavior

My personal expectation is that a changed seed would vary the data sampler's seed as well. However, this may conflict with your views on what changing the seed should change. Thus the proposal for a separate seed to control for data reproducibility.

**Comment by janEbert** [comment]
What I said about LLM Foundry is actually unrelated, after taking a deeper look there as well. There is a surprising thing in the implementation, but I'll move discussion over to that repo (https://github.com/mosaicml/llm-foundry/issues/1676).

**Comment by mvpatel2000** [comment]
Thanks for investigating this!
