### ISSUE TITLE
pytests should use `trainer.__init__()` not `hparams` where feasible

### ISSUE THREAD

**Issue by hanlint** [mosaicml/composer#385]
Tests are good code snippets for how to use our trainer. However, most of our tests of trainer functions (e.g. checkpointing, DDP) all rely on the hparams system, which makes it difficult for external users who are mostly non-yahp-based to grok our code. We should migrate all the tests to using `trainer=Trainer(..)` approaches.

**Comment by mvpatel2000** [comment]
Hparams is gone. Congrats @hanlint
