### ISSUE TITLE
Unify `SyntheticBatchPairDataset` and `SyntheticPILDataset`

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#388]
Currently [`SyntheticPILDataset`](https://github.com/mosaicml/composer/blob/8b625ad167f9838580e907c7b411b63f539080c3/composer/datasets/synthetic.py#L133) reuses a lot of the code from [`SyntheticBatchPairDataset`](https://github.com/mosaicml/composer/blob/8b625ad167f9838580e907c7b411b63f539080c3/composer/datasets/synthetic.py#L25). It would be great to unify them as much as possible, as discussed in #320. Comments won't link properly so I copy them below:

@ravi-mosaicml:
>Could the `SyntheticPILDataset` internally use a `SyntheticBatchPairDataset` to generate the tensors, and then wrap it in a PIL image (and apply the transformations) on `__getitem__`.? I think that would clean up the code.

@growlix:
>I'm not quite sure how to internally use a `SyntheticBatchPairDataset` to generate the data for `SyntheticPILDataset` because `SyntheticBatchPairDataset` generates the tensors upon the first call to `__getitem__`, and `SyntheticPILDataset` would need to override `__getitem__`. It might be possible to change `SyntheticBatchPairDataset` to generate the data on init, but the comment for `__getitem__` in `SyntheticBatchPairDataset` makes it seem as though the data need to be generated upon the first call to `__getitem__` so that they're on the correct gpu.

**Comment by ravi-mosaicml** [comment]
Implemented in #263
