### ISSUE TITLE
time string objects should accept integer values as well

### ISSUE THREAD

**Issue by siriuslee** [mosaicml/composer#415]
Variables like `max_duration` or `save_interval` should accept integers in addition to strings. Integers should usually be cast to epochs, (e.g. `10` -> `"10ep"`), unless the specific case suggests a different handling.

**Comment by ravi-mosaicml** [comment]
I'm hesitant to automatically infer a unit, unless if if the same unit would be used across all types of models, including both nlp and vision. For example, for nlp tasks that train only one epoch, then I don't think it would make sense to checkpoint epochs.

**Comment by hanlint** [comment]
We can scope this down to just the `Trainer` init signature, but epochs is a untuitive default unit that everyone is aware of.
