### ISSUE TITLE
Replace the run directory with a `log_file` API

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#421]
The run directory is used as a staging area for callbacks, loggers, and the checkpointer to write data. Other callbacks can periodically read from this folder, for example to upload files to an object store.

This design poses some challenges:
1. Impossible to clean while training: Once a file is written to the run directory, it cannot be deleted while training. There is no guarantee when callbacks that read the run directory will fire
2. Additional user complexity. The user must pay attention to where the run directory is stored. All paths that a user provides (such as the checkpoint folder or file logger file) are relative to the run directory, which is confusing.
3. Performance degradation: Files in the run directory must be copied before being uploaded. If the run directory is on a slow disk, this blocks the training process.

As an alternative, we can expose a `loggger.log_file` API. Design proposal here: https://www.notion.so/Artifact-Logging-API-d3754be3ec874233910cb0c4f23c9d32

The advantages of this approach are that:
* Files would not need to be kept around in a local directory once uploaded
* Users would not need to worry about this temporary staging directory

**Comment by ajaysaini725** [comment]
We still need to keep files separated per-rank so that the files written by each rank don't overwrite each other right? Like if a user specifies `filename.txt` for `file_logger` then each rank will be writing to a file called `filename.txt` unless we somehow split it by rank.

Also, what happens in the case where the user wants to save files locally and not upload them? Without a `run_directory` we can assume all paths provided by the user are local to `cwd` but this opens up the possibility of files from the current run overwriting previous results - which can be okay we can just throw an error if the file exists.

**Comment by ravi-mosaicml** [comment]
> We still need to keep files separated per-rank so that the files written by each rank don't overwrite each other right? Like if a user specifies `filename.txt` for `file_logger` then each rank will be writing to a file called `filename.txt` unless we somehow split it by rank.

Good point, the implementation for the log file API would need to include `dist.get_global_rank()` somewhere in the object key name. For flexibility, perhaps the user can specify a format string.

> Also, what happens in the case where the user wants to save files locally and not upload them? Without a `run_directory` we can assume all paths provided by the user are local to `cwd` but this opens up the possibility of files from the current run overwriting previous results - which can be okay we can just throw an error if the file exists.

A local folder would also function as an object store provider. (Libcloud does have this as a backend, but their implementation is pretty cumbersome to use, so I think we could just take a `Union[str, ObjectStoreProvider]`, and if it's a string, then it's a local folder. (behind the scenes, we can convert a string into the Libcloud local folder option, to simplify the codepath).
