### ISSUE TITLE
Fix model surgery so `Event.INIT` can be removed from Trainer `__init__`

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#43]
Right now model surgery does not work after the model parameters have been passed to an optimizer. As a result, we call the `Event.INIT` (which is used by model-modifying methods such as Blurpool and SqueezeExcite) call back in the Trainer `__init__` before the optimizer is constructed rather than in the training loop.

This yields API complications because the user cannot pass a pre-constructed optimizer into the Trainer `__init__`.

We need to get surgery working properly and test it on Blurpool and SqueezeExcite to make sure there are no regressions.

**Comment by ravi-mosaicml** [comment]
@anisehsani curious about the status of this one? If we can get this merged in, then I think we should be able to remove `Event.INIT` and move the `Event.TRAINING_START` right before all the ddp wrapping begins. This would help clean up the trainer, as then no events would fire in `__init__`.

**Comment by dblalock** [comment]
Not positive, but I think the path to getting this working cleanly is to make it easy to `add_param_group` to the optimizer after its construction (but still before ddp). And to default to adding the all the model's params to a group. As long as the optimizer's `default_dict` has the same hparams as would have been used when passing params in at `__init__`, this should end up with equivalent behavior (in theory).

The more comprehensive solution, which would also enable dynamic factorization, quantization, channel pruning (?), etc, is to work around DDP needing the params and their shapes frozen, which would solve this as a special case. But that's probably a lot harder.

**Comment by ravi-mosaicml** [comment]
This issue presents an interesting API challenge:

`optimizers` depends on the model
`schedulers` depends on the optimizers and steps_per_epoch

It may make sense to wait until after #146  is implemented, as then `steps_per_epoch` would no longer required to initialize schedulers

**Comment by ravi-mosaicml** [comment]
Closing for #249 and #157
