### ISSUE TITLE
Loading a checkpoint overwrites `max_duration`

### ISSUE THREAD

**Issue by siriuslee** [mosaicml/composer#441]
Loading a checkpoint overwrites `max_duration`. This makes it pretty difficult to resume training from a late-in-training checkpoint. To do so, you'd have to manually extract optimizer and scheduler states, at least, and then create a new trainer with `load_only_weights=True`. I'm not exactly sure what the right solution is, but this workaround is too cumbersome to be reasonable.

**Comment by ravi-mosaicml** [comment]
Makes sense, the `max_duration` argument passed into the trainer should override whatever is in the checkpoint (i.e. `max_duration` should be a skip serialization field).
