### ISSUE TITLE
Checkpoints stored in run directory cannot have ":" in their name

### ISSUE THREAD

**Issue by siriuslee** [mosaicml/composer#442]
By default, the run directory contains a timestamp with ":" in its name. If the run directory is uploaded to an object store, any checkpoints within it cannot be used by `CheckpointLoader` because it parses the `load_path` as a URL: https://github.com/mosaicml/composer/blob/dev/composer/trainer/checkpoint.py#L93-L99

**Comment by siriuslee** [comment]
It seems that there is a handy workaround for this for now. The `RunDirectoryUploader` has an argument `object_name_prefix`. This argument defaults to the "run directory" if not provided, which is the timestring that breaks things. If `object_name_prefix` is specified by the user, then the checkpoints can be loaded properly.

**Comment by ravi-mosaicml** [comment]
This will be fixed -- will remove colons from the time string before using that as a folder name. Though allowed, I don't think colons should be used in folder names....
