### ISSUE TITLE
Refactor parts of `_train_loop()`

### ISSUE THREAD

**Issue by Landanjs** [mosaicml/composer#444]
There are several pieces of code that are useful for the training loop, but may not need to be hardcoded/defined within the training loop. Some examples are checkpointing, computing metrics and logging, and mixed precision training. These could be potentially moved to Callbacks/Algorithms, reducing the amount of code in `Trainer` and may make the code more readable. Ideally, this would not change how `Trainer` is configured, instead bits of code would be refactored into standalone classes.

I will try to scope this out and elaborate more after v0.4, but happy for more discussion!

**Comment by mvpatel2000** [comment]
Closing as partially done and partially not on roadmap
