### ISSUE TITLE
Embed the algorithm and model metadata directly in the docs

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#448]
#437 removed the README.md files in the model and algorithms folder (since we use docstrings for module-level docs). Moved the table generation source to docs/source/tables. Need to refactor these files and add the tables into the sphinx docs.

**Comment by ravi-mosaicml** [comment]
Depends on #446 and #447, so going to wait on it.

**Comment by hanlint** [comment]
Ah, I missed the `README` getting deleted. I think we definitely want `README` for the `algorithms` and `model` folders, as they show up when users are navigating github. It's OK if they are duplicated in the module-level docs.

**Comment by mvpatel2000** [comment]
Closing since it's done :)
