### ISSUE TITLE
Checkpoint Metadata

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#451]
Should `grad_accum` and `precision` be persisted in checkpoints? If so, how should we support allowing the user to override these fields when resuming from a checkpoint.

Or, are these fields additional metadata that should be recorded in a checkpoint -- but not used when resuming from training?

Are there other metadata fields that we should persist in a checkpoint? (The device? Scale Schedule ratio? Whether deterministic mode was used? The checkpoint load path? E.g.) While the yahp code path records all of this information by dumping the yaml next to the checkpoint, we do not currently save this information in the checkpoint for the non-yahp code path.

_Originally posted by @hanlint in https://github.com/mosaicml/composer/issues/445#issuecomment-1034384445_

**Comment by mvpatel2000** [comment]
Closing. We have some metadata logged now
