### ISSUE TITLE
See stack trace for ranks > 0 when tests fail

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#477]
## 🚀 Feature Request

Right now, if a rank other than rank 0 crashes while running tests, you end up with timeout errors or `Connection closed by peer` errors without any stack trace from the rank that crashed. It would be very helpful to see logs / stack traces for ranks other than rank 0 in the case of a test failure.

**Comment by ravi-mosaicml** [comment]
Ah yes. I think we will need to monkeypatch the distributed barriers to use timeout barriers in tests, so they exit without blocking forever.

**Comment by ravi-mosaicml** [comment]
Closed via #805, which logs the non-rank-zero stdout and stderr as Jenkins artifacts.
