### ISSUE TITLE
Add Javascript to autoscroll the docs sidebar to the currently open docs entry

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#498]
It would be nice if the sidebar on the docs site autoscrolled down to the currently open page. I think this can be done via some custom javascript.

**Comment by hanlint** [comment]
yeah agreed this is a bit annoying when trying to look at different method cards, as each time i click on one, the scroll bar goes to the top.

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri
