### ISSUE TITLE
Document difference between *Hparams and associated class

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#501]
We should explicitly describe the difference between usage scenarios for `Hparams` objects vs the classes they end up instantiating (e.g. `TQDMLogger` vs. `TQDMLoggerHparams`). I think the right place to do this is probably in every `*Hparams` docstring. I am thinking something like:

> `*Hparams` is used to instantiate `*` via YAML configs instead of calling it directly.

but I might be missing something because I'm not an expert.

**Comment by ravi-mosaicml** [comment]
Need to add a YAHP tutorial, and then we can link in each docstring to the yahp tutorial.

**Comment by mvpatel2000** [comment]
YAHP is gone :)
