### ISSUE TITLE
DataSpec `num_samples` is not set correctly for IterableDataset

### ISSUE THREAD

**Issue by abhi-mosaic** [mosaicml/composer#504]
I think this line needs to be modified to support IterableDatasets.

https://github.com/mosaicml/composer/blob/93b1c3459e88dacbe41650bc2ce039fb340609af/composer/core/data_spec.py#L76

For IterableDatsets, this would actually return the `per_device_num_samples`, not the overall `num_samples`. We set length in this way to comply with how PyTorch's Dataloader supports `len(dataloader)`. The length of a Dataloader is the length of the sampler for Map-style Datasets, and the length of the device's dataset for IterableDataset:

https://github.com/pytorch/pytorch/blob/0942af7c4b22d5219fb30799ac4c16db6940f62b/torch/utils/data/dataloader.py#L386-L413

@ravi-mosaicml I did a quick search and I don't think this is being used anywhere yet... right? Also looping in @knighton.

**Comment by ravi-mosaicml** [comment]
For iterable datasets, `num_samples` should be set explicitly in the `DataSpec` constructor. This default behavior is to support the (novice) case where each worker loads the entire dataset, and a distributed sampler is used to subsample per worker.

**Comment by ravi-mosaicml** [comment]
Going to close for now; but please re-open if the default behavior for the `DataSpec` should be changed -- i.e. we could require that `num_samples` be set explicitly, and not infer that from `len(dataloader.dataset)`.
