### ISSUE TITLE
Training run processes do not stop at the end of training

### ISSUE THREAD

**Issue by Landanjs** [mosaicml/composer#51]
## Environment

mosaicml/research:latest docker container on 3080s.

## To reproduce

Command: 
`python examples/run_mosaic_trainer.py -f composer/yamls/models/resnet50.yaml --loggers wandb --loggers.wandb.entity mosaic-ml --loggers.wandb.project landan-random --callbacks speed_monitor lr_monitor --callbacks.speed_monitor.window_size 100`

I believe Cory saw hanging at the end of the CIFAR-10 benchmark as well, so that may be sufficient to reproduce the bug.

## Expected behavior

All (sub)processes to be killed at the end of training.

## Additional context

Training runs hang at the end of training. This means the processes will continue to run although training is complete.

**Comment by hanlint** [comment]
@Landanjs can you confirm that this is now fixed with #65 ?

**Comment by Landanjs** [comment]
It worked with a CIFAR10 run! 😱 Woohoo, thanks!
