### ISSUE TITLE
Confusing `Scheduler` and `Schedulers` types

### ISSUE THREAD

**Issue by jfrankle** [mosaicml/composer#510]
It makes sense to have types like Scheduler and Schedulers but when trying to use the library, that s is easy to miss and explicitly laying out the type in things like Trainer initialization would help.

**Comment by ravi-mosaicml** [comment]
Good point, in the docstrings, we should use the `Scheduler | List[Scheduler] | Tuple[Scheduler]` notation rather than `Schedulers`.
