### ISSUE TITLE
Clean data access interface for `InMemoryLogger`

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#513]
## 🚀 Feature Request
Currently data is stored in the `InMemoryLogger` in a `dict` in the form

```
{key: [(Timestamp, LogLevel, metric), (Timestamp, LogLevel, metric), ...]
      ...
}
```

This is not a particularly humane format to store the data. Doing much of anything with it requires a user to write their own code to extract and collate the data into a different format. It would be great if the `InMemoryLogger` had a method(s) to return its data in a more easily usable form. Maybe something like 

```
print(in_memory_logger.get_data(data="accuracy/val", interval="epoch"))
>>> {"accuracy/val": [15, 25, 31, 33, ...], "epoch": [0, 1, 2, 3, ...]}
```

**Comment by ravi-mosaicml** [comment]
@growlix assigned to you! Feel free to add helper methods that would make sense.
