### ISSUE TITLE
Docs for Methods has unreadable links for methods - Possibly in dark mode?

### ISSUE THREAD

**Issue by jzf2101** [mosaicml/composer#515]
See [screenshot](https://docs.mosaicml.com/en/latest/method_cards/methods_overview.html):

<img width="1105" alt="Screen Shot 2022-02-17 at 6 01 54 PM" src="https://user-images.githubusercontent.com/1373035/154586180-70b42c3b-b30f-4e61-a6f7-bc44a60c47c2.png">

**Comment by hanlint** [comment]
Thanks -- thought we had fixed this, but apparently not. @nqn can you do a fix?

**Comment by nqn** [comment]
<img width="1120" alt="Screen Shot 2022-02-17 at 2 29 52 PM" src="https://user-images.githubusercontent.com/897374/154588389-d97b2c75-84d5-4725-9ba8-e470faf54b78.png">

I'm getting white background on safari and chrome. Which browser are you using, and/or are you building docs locally?
For local hosting, you may have to invalidate the browser cache (haven't found a way around this, server side).

**Comment by jzf2101** [comment]
I'm not building docs locally and I'm using Safari

**Comment by nqn** [comment]
Found the issue - working on it now
