### ISSUE TITLE
Welcome Tour Before Using Composer in Sidebar?

### ISSUE THREAD

**Issue by jzf2101** [mosaicml/composer#517]
I personally would want to try out `Welcome Tour` before `Using Composer` 

<img width="235" alt="Screen Shot 2022-02-17 at 6 06 52 PM" src="https://user-images.githubusercontent.com/1373035/154586581-fd4b1876-fe92-4c69-a5dd-c9993bb4ef3f.png">

**Comment by ravi-mosaicml** [comment]
Closing as we no longer have "Using Composer" under getting started.
