### ISSUE TITLE
Logger docstrings cleanup

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#521]
- [x] For https://mosaicml-composer--499.com.readthedocs.build/en/499/api_reference/composer.loggers.html#module-composer.loggers, could you elaborate more on the logger system architecture? I think a flow chart here could be helpful -- e.g. algorithms and callbacks can make calls to the logger, which then routes the calls to the logging backends. For the example logger, would it make sense to also show how flushing may want to be done on batch_end (after some interval) or epoch_end?
- [x] Could you move the example to https://mosaicml-composer--499.com.readthedocs.build/en/499/api_reference/composer.core.logging.base_backend.html#composer.core.logging.base_backend.LoggerCallback, and then reference this example from the module-level docstrings?
- [x] For the file logger filename, can you comment that this is relative to the run directory (and link to `composer.utils.run_directory`?)
- [x] For the hparam classes, can you enumerate the parameters (similar to what you did for the algorithm hparams)? From the docs page, it isn't clear what the values are for each hparams class. (For the individual parameters, I think it's cool to say something like `see FileLogger` rather than repeating the docstring)
- [x] For the in memory logger, what does "Be sure to confirm logger.backends index." mean?
- [x] For the wandb logger, can you have the `run_directory` auto-link to `composer.utils.run_directory`

_Originally posted by @ravi-mosaicml in https://github.com/mosaicml/composer/issues/499#issuecomment-1043735660_

**Comment by growlix** [comment]
For the example, I'm tempted to keep it simple in the docstring and also link to the [logging tutorial](https://www.notion.so/Logging-locked-74196d271b7c43e494ba6cbd5511f58c) (and possibly the source for a LoggingCallback).

**Comment by ravi-mosaicml** [comment]
Fixed in #544
