### ISSUE TITLE
Torchvision-like transform APIs are missing and/or inconsistent

### ISSUE THREAD

**Issue by dblalock** [mosaicml/composer#530]
This is a (minor) API consistency problem. Right now {augmix, randaug, colout} have {AugmentAndMixTransform, ColOutTransform, RandAugmentTransform}, while cutout does not have a torchvision-compatible transform at all. We should either ensure that they all have a transform version, or that none of them do.

Also, these are each implemented somewhat differently. One is a generic python class while two subclass `nn.module`. And the Augmix one is not named in the same manner.

Note: Other augmentations also lack transform wrappers, but can't easily get them since they also rely on seeing the labels. Specifically: mixup, cutmix, label smoothing.

**Comment by mvpatel2000** [comment]
Closing as not on roadmap for now
