### ISSUE TITLE
composer.models cleanup

### ISSUE THREAD

**Issue by A-Jacobson** [mosaicml/composer#536]
Putting this here to open discussion

The models module could use some general cleanup:
- Move `ComposerClassifier` out of `base.py` as it's not a base class.
- Move `ComposerTransformer` into `base.py` as it is a base class (pending work into general transformer factory)
- Unify naming scheme for models - some models are `Composer<Architecture>` some `Architecture`
- Move metrics out of `losses.py` and `nlp_metrics.py` into a separate metrics module.
- Maybe remove soft_cross_entropy as default pytorch CEloss supports dense labels now (depending on our supported pt versions)
- Initializers to their own module or removed (ongoing discussions about these).

**Comment by ravi-mosaicml** [comment]
Closing for #834
