### ISSUE TITLE
Replace our EfficientNet model with either torchvision or TIMM

### ISSUE THREAD

**Issue by Landanjs** [mosaicml/composer#539]
## Motivation

We have a custom EfficientNet model since we did not have access to a third-party implementation. Torchvision released an efficientnet model and we have TIMM integration, so we should move to use either of these models to align with the research community and reduce necessary maintenance with a model implementation. Also, torchvision/TIMM will allow us to easily access the entire model family instead of using a single model as we are doing now.

**Comment by mvpatel2000** [comment]
Closing as models will be removed eventually
