### ISSUE TITLE
Sensible naming scheme for logging classes

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#541]
Seeing as:
- The `LoggerCallback`-based classes (e.g. `FileLogger`) have "Logger", not "Callback" in their name.
- Referring to the `LoggerCallback`s as `LoggerCallbacks` feels ungainly and seems confusing, because it's focusing on _how_ they work instead of _what_ they're used for.
- Most documentation and instructional material refers to `LoggerCallback`s as "Loggers", which overloads the term.
- `Trainer` has a `loggers` hparam that takes a list of `LoggerCallback`s, not `Loggers`s.
- We renamed `LoggerBackend` to `LoggerCallback`, but the `Logger` class still uses `backend/backends` as a parameter and attribute name.

I propose that we come up with a more sensible naming scheme. I'm not super opinionated, but I have a few ideas. Perhaps we change `Logger` to `LogRouter`, `LoggingController`, or `LoggingFrontend`. Thoughts @hanlint, @ravi-mosaicml, @siriuslee

**Comment by hanlint** [comment]
I agree with a rename, but I'd like to see some concrete suggestions. `LogRouter` is clear, but that also means users will need to call:
```
log_router.metric_log(..)
```

and many of our signatures would have:

```
def match(state: State, log_router: LogRouter):
```

which is non-intuitive syntax.

**Comment by growlix** [comment]
I suppose the noun/verb ambiguity of "log" could be confusing. Tho maybe not because it's a class, not a method? I wonder if `Logger` -> `LoggingRouter`/`LoggingFrontend` and `LoggerCallback` -> `Logger`?

**Comment by hanlint** [comment]
I'm of the strong held opinion that we should not rename `Logger`. It's really the main user-facing API. The fact that we have these different destinations is an implementation detail, and the naming should reflect that.

If we accept that as a constraint, I'm not sure of any good options to handle this.

**Comment by ravi-mosaicml** [comment]
Discussed offline with @growlix; will rename `LoggerCallback` to `LoggerDestination`.

The rational was that `LoggerCallback` emphasizes the implementation (that it's a callback) over what it actully does (that it's where logging calls are sent). `LoggerBackend` was also considered, but backend isn't as clear as destination.
