### ISSUE TITLE
Python 3.7 support (for use with colab)

### ISSUE THREAD

**Issue by codestar12** [mosaicml/composer#55]
## 🚀 Feature Request
add support for python 3.7 build

## Motivation

I wanted to play with composer but was not able to install via pip because google Colab runs in a python 3.7 environment

**Comment by Averylamp** [comment]
Thanks for the issue!  We will be working on this in one of our dependencies that requires Python 3.8 for now. Stay tuned!

**Comment by ravi-mosaicml** [comment]
Python 3.7 support should be in the next release. The following PRs address the compatibility issues with 3.7:

* https://github.com/mosaicml/yahp/pull/71
* https://github.com/mosaicml/composer/pull/68

**Comment by codestar12** [comment]
@ravi-mosaicml thanks for getting to this so quickly!
