### ISSUE TITLE
Error early for `selective backprop` if used as an `Algorithm`

### ISSUE THREAD

**Issue by siriuslee** [mosaicml/composer#552]
Selective backprop has a number of checks in its functional form that will not be caught until you try to use it (https://github.com/mosaicml/composer/blob/dev/composer/algorithms/selective_backprop/selective_backprop.py#L97-L113). Because it is based on a schedule, this might not happen until late into training, which is a bad user experience.

Try to catch as many of these as possible (preferably all of them) on init or in the first batch.

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri. We're open to community suggestions!
