### ISSUE TITLE
Override `max_epochs` on resume from checkpoint with SSR

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#56]
When resuming from a checkpoint, `max_epochs` currently defaults to the original `max_epochs` which prevents users from being able to train for more than the original `max_epochs` when resuming from a checkpoint. 

It would be good to be able to resume from checkpoint and train for more epochs than the original `max_epochs`. However, we need to come up with a scheme to make this work with `scale_schedule_ratio` because scale schedule ratios are computed assuming that `max_epochs` does not change.

How should we go about handling this?

**Comment by ravi-mosaicml** [comment]
Fixed via #445....the SSR and max duration are not persisted in a checkpoint, so whatever values are passed to the trainer upon checkpoint resume will be used.
