### ISSUE TITLE
Test support for Pytorch v1.10

### ISSUE THREAD

**Issue by hanlint** [mosaicml/composer#58]
Run regression tests on pytorch v1.10 (https://pytorch.org/blog/pytorch-1.10-released/)

**Comment by ravi-mosaicml** [comment]
What would we like to run for regressions?

**Comment by hanlint** [comment]
Before we officialy support pytorch v1.10, let's get
* jenkins tests running with this version
* resnet-50 imagenet baselines

**Comment by ravi-mosaicml** [comment]
Closing issue as we ran regressions for the v0.5.0 release, and Jenkins tests on Pytorch 1.10 + Python 3.9
