### ISSUE TITLE
Clean up ALiBi implementation to not require passing private modules

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#582]
ALiBi replaces a model's non-ALiBi attention with a a module that has ALiBi implemented. This currently requires users to pass paths to modules/classes (for the class form) or actual modules/classes (for the functional form). which is ungainly and can sometimes require users to reference private classes. A possible solution would be for ALiBi to just check the model class against a database/mapping file that contains the relevant hparams for each model class.

Thoughts @moinnadeem, @ravi-mosaicml?

### From #457

Ravi:
> For alibi, should _gpt2_alibi and _attn be public and documented be documented? In the hyperparameters, we mention "composer.algorithms.alibi._gpt2_alibi._attn". I think it's a bit confusing to recommend to users to import a private class.

Matthew
> ALibi changes the self-attention computation. The self-attention implementation and model structure (i.e. module/attribute tree) are totally inconsistent across libraries (and even within libraries), which makes the Alibi implementation a bit complicated—it needs to be bespoke for each model class.
>
> For example, in HuggingFace's GPT-2 (which is what we use for our GPT-2), self-attention is a method named `_attn` of a `GPT2Attention` module (i.e. `transformers.models.gpt2.modeling_gpt2.GPT2Attention._attn`). The Alibi-enhanced attention for our GPT-2 is the code for `transformers.models.gpt2.modeling_gpt2.GPT2Attention._attn` with a small modification that implements Alibi. To ensure that `GPT2Attention` behaves as expected, the Alibi-enhanced attention has the same name as the attention method it replaces (`_attn`).
>
> I agree it's weird to have users import a private class, but it's necessary given the current Alibi implementation. I dunno if it makes it any better, but they shouldn't be expected to use anything in `composer.algorithms.alibi._gpt2_alibi` for anything other than passing into `apply_alibi`. Even the `Alibi` algorithm takes strings pointing to `..._gpt2_alibi._attn` and `..._gpt2_alibi.enlarge_mask` instead of the actual functions.
>
> Maybe a nicer implementation would have a  database/mapping file that contained the relevant hparams for each model class? Happy to file an issue for that and get to it post-release, unless you think it should be addressed immediately.

_Originally posted by @growlix in https://github.com/mosaicml/composer/issues/457#issuecomment-1041020136_

**Comment by moinnadeem** [comment]
I think the mapping between a Class (ie. `isinstance`) and the relevant hparams regarding the attention implementation works with me. This has some implications about "Composer defaults" that @hanlint and I chatted about last week. I think we should contain an extensible implementation that contains Composer defaults, and make it easy for the user to add a new item to the matrix if they add a new Composer model.

I get a feeling that this touches on more than ALiBi as well. This is likely important for all of surgery.

**Comment by hanlint** [comment]
Since Alibi is probably restricted to the scope of HuggingFace model, I am in favor of putting a mapping here in alibi of huggingface transformer names to the right attention module. We should of course allow explicit user provided for cases where we get it wrong or there is a custom model being tested..

**Comment by ravi-mosaicml** [comment]
This issue hits at #171 and the need for a better registry design. While passing paths to modules is messy, it does alleviate the need to have a registry / mapping of a string name to a python class.
Would we expect users to want to extend this registry? Or are there going to be a limited number of options?

**Comment by growlix** [comment]
Given that ALiBi has to be implemented in a model-specific way, users will probably have to implement custom ALiBis for custom models. If they're already doing that, I don't think it's much of a stretch to require them to decorate their alibi functions with a `register_alibi_attn` or manually add it to a registry somewhere.

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri
