### ISSUE TITLE
Consider refactoring the trainer loop for readability

### ISSUE THREAD

**Issue by hanlint** [mosaicml/composer#586]
https://github.com/mosaicml/composer/pull/531#pullrequestreview-890525718

> The "Annotated Trainer Loop" section highlighted how much work we have so the code is indeed "easily readable and understood". I'm OK keeping this section for now but would like to refactor the code, so this section isn't necessary -- and the code speaks for itself.

**Comment by ravi-mosaicml** [comment]
Closing for #444
