### ISSUE TITLE
Launch DDP processes before initializing trainer

### ISSUE THREAD

**Issue by jbloxham** [mosaicml/composer#59]
## 🚀 Feature Request
Our current trainer relaunches itself N times to create N processes for DDP. The problem with this is that DDP does so by rerunning the very script that launched the trainer in the first place. This is problematic for any user invoking DDP via a custom script, and also for testing.

The canonical solution to this problem is to provide a launch executable that wraps a user provided script to initialize a trainer. The launch executable runs the script N times to create N processes. This appears to be the direction that many ML frameworks, including DeepSpeed, are moving towards.

## Motivation

This will simplify testing and allow us to accurately calculate coverage metrics. This is also essentially a prerequisite to integrating the trainer with DeepSpeed, which also uses an executable.

**Comment by ravi-mosaicml** [comment]
Closed via #65
