### ISSUE TITLE
Automated Tests for Code in README.md files

### ISSUE THREAD

**Issue by jfrankle** [mosaicml/composer#590]
Write an automated test that goes through method cards, extracts the code, and runs them.

**Comment by dblalock** [comment]
Can we just convert these to rst files (README.md -> README.rst)? If so, we should be able to just use doctest like in the rest of our docs. Would also let us [include](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include) the method cards as the module docstrings and avoid duplicate code + language there.

**Comment by ravi-mosaicml** [comment]
Unfortunately, for readme files visible on github.com, we cannot use doctest.

**Comment by mvpatel2000** [comment]
Closing -- we do this with https://github.com/nschloe/pytest-codeblocks now :)
