### ISSUE TITLE
Tracking and logging elapsed (wall clock) time

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#608]
## 🚀 Feature Request

It seems like elapsed wall clock time is not tracked or logged (except via W&B). This means users have no straightforward way of quantifying time-to-train.

## Implementation

Add a wall-clock unit (e.g. `second`) to `TimeUnit`

Add a wall-clock unit to `Timestamp`

Track elapsed time in `Timer`. Something like:

```
Timer():
    def __init__(self):
        ...
        self._previous_time = Time(time.now(), TimeUnit.second)
        self._current_time = self._previous_time

    ...

    def get_timestamp(...):
        self._current_time = Time(time.now(), TimeUnit.second)
        elapsed_time = self._current_time - self._previous_time
        self._previous_time = self._current_time
        return Timestamp(
            second=elapsed_time
            ...
        )
```

**Comment by ravi-mosaicml** [comment]
Yup! This is in the roadmap. Closing for https://github.com/mosaicml/composer/issues/256
