### ISSUE TITLE
Crashed `composer` runs occasionally result in zombie processes

### ISSUE THREAD

**Issue by jbloxham** [mosaicml/composer#623]
When testing a GPT run with RoCE and a streaming dataloader, crashed runs occasionally created defunct `python3.8` processes that didn't respond to SIGKILL. The exact cause is unclear, but this will potentially cause increasing performance degradation on systems that repeatedly run `composer`, even when new Docker containers are started.

**Comment by ravi-mosaicml** [comment]
Fixed in https://github.com/mosaicml/composer/pull/840.
