### ISSUE TITLE
Pre-Commit Hooks

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#642]
Configure pre-commit hooks to run `make style` and `make lint` before every commit. This should significantly limit the number of commits we see where Jenkins fails due to linting issues. Pre-commit hooks can be configured via https://pypi.org/project/pre-commit/.

**Comment by hanlint** [comment]
Hello @RishiKumarRay , our `Makefile` does a `make style` to auto-format the code with `isort`, `yapf`, and other linters.

**Comment by RishiKumarRay** [comment]
@hanlint @ravi-mosaicml i would like to work on this assign me

**Comment by hanlint** [comment]
@RishiKumarRay sounds good! We'd like to use the `pre-commit` package (https://pre-commit.com/) and add a `.pre-commit-config.yaml` file to run `make style`.

**Comment by RishiKumarRay** [comment]
@hanlint i tried setting up , this is what i have written in pre commit file 
![Screenshot from 2022-03-06 19-01-15](https://user-images.githubusercontent.com/87641376/156925454-01231be7-2e1d-4018-af2a-810c8e3a93a7.png)
