### ISSUE TITLE
Convert `.. code-block::` in the docstrings to `.. doctest::` or `.. test-code::`

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#659]
Python code blocks  (e.g., `.. code-block:: python` or `.. code:: python`) in the docstrings are not tested and can easily become out of date. Instead, they should use doctest, which can be done via `.. doctest::` or `.. test-code::`. Any test setup (that should not be printed in the documentation but needs to run to generate necessary fixtures) can be in a `.. test-setup::` block or the global `docs/source/doctest_fixtures.py` file.

**Comment by mvpatel2000** [comment]
Closed as mostly done.
