### ISSUE TITLE
Move the `max_duration` from `state` into `state.timer`

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#660]
It would help simplify the API -- especially in the schedulers -- if the timer was aware of the `max_duration`. Specifically, calls like this currently fail:

`if state.timer < Time(0.5, "dur"): do_something()`.

Instead, these calls have to look like the following

```python3

time = Time(...)

if time.unit == TimeUnit.DURATION:
  if state.get_elapsed_duration() < time: do_something()
else:
  if state.timer < time: do_something()
```

If the Timer was aware of `max_duration`, then it could respond to the above queries.
The `get_elapsed_duration` helper method should also be moved from the `state` into the `timer`.

**Comment by hanlint** [comment]
Sounds good, would you be amenable to still keeping a `max_duration` property on `state` that links to `state.timer.max_duration` ?

**Comment by ravi-mosaicml** [comment]
> Sounds good, would you be amenable to still keeping a `max_duration` property on `state` that links to `state.timer.max_duration` ?

Sure, though that would be the only timer property directly on the state.

**Comment by hanlint** [comment]
I think that's OK, its a unique property in `Timer` compared to the others that track time.

**Comment by ravi-mosaicml** [comment]
Closing this issue as #879 removed the `Timer` class. Instead, the current timestamp is bound directly to the state.
