### ISSUE TITLE
Checkpoints are sometimes created twice on the final iteration

### ISSUE THREAD

**Issue by jbloxham** [mosaicml/composer#681]
Checkpoints can sometimes be created twice within the final iteration. For this to happen, several conditions must be true:

1) The checkpoint interval is in units of batches
2) The final batch in training lies on a checkpoint interval

If this happens, `should_checkpoint` will return `True` for both the final `BATCH_END` and `EPOCH_END` events, and the final checkpoint will be created twice.

**Comment by ravi-mosaicml** [comment]
Fixed in #687 

See https://github.com/mosaicml/composer/blob/dc5184f03b419430bc2798600f1bac8e79d4e564/composer/callbacks/checkpoint_saver.py#L23-L76
