### ISSUE TITLE
tutorial url for CallbackHparams doesn't exist

### ISSUE THREAD

**Issue by dlwh** [mosaicml/composer#717]
The url pointed to in https://github.com/mosaicml/composer/blob/dev/composer/callbacks/callback_hparams.py#L35 doesn't exist: https://docs.mosaicml.com/en/latest/tutorials/adding_models_datasets.html#trainer-with-yahp

(I'd like to add a callback...)

**Comment by hanlint** [comment]
@dlwh thanks for pointing this out! We'll put in a fix for that link. 

For now, you can view the page at an old version of our site: https://docs.mosaicml.com/en/v0.3.1/tutorials/adding_models_datasets.html#trainer-with-yahp
