### ISSUE TITLE
Progressive resizing applied to dataloader

### ISSUE THREAD

**Issue by codestar12** [mosaicml/composer#728]
## 🚀 Feature Request

Implement progressive resizing a data loader transform. 

## Motivation

I was playing around with the progressive resizing algorithm. Both the functional method and the algorithm. I verified that it was working. My GPU memory use was lower until it resized to the original imager. But as noted in the docs I was bottlenecked early in training not seeing what I would expect in terms of speedup. It occurred to me part of this is that the current implementation resizes the images _after_  the data loader has already resized the images. This means we are paying for the same transformation twice.

## [Optional] Implementation

Could this be implemented as a way to rebuild the data loader during training or modify transformations during training with a composer *algorithm*?

## Additional context

If there is already some easy way to do this, or I misunderstood the current progressive resizing implementation I apologize.

**Comment by mvpatel2000** [comment]
Closing as won't support -- per offline discussion, I think it's fine to keep as is
