### ISSUE TITLE
FFCV Integration

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#737]
Creating an issue to track FFCV Integration

Dependencies:
- [x] #724 
- [x] #424 
- [x] #672 
- [x] Add test cases for FFCV ([#803](https://github.com/mosaicml/composer/issues/803#issue-1176097563) )
- [x] Add non-yahp way to create the FFCV dataset ([#799](https://github.com/mosaicml/composer/issues/799#issue-1176037182) )

**Comment by dskhudia** [comment]
> Add non-yahp way to create the FFCV dataset

https://github.com/mosaicml/composer/pull/815

**Comment by dskhudia** [comment]
> use_synthetic 

@ravi-mosaicml 

The way SyntheticBatchPairDataset is created won't work with FFCV in the spirit of synthetic. FFCC will create a full dataset (i.e., no difference in its size and data it needs to write and then load) with the current SyntheticBatchPairDataset defaults. One way to mitigate this is to use smaller length synthetic dataset. Does it still make sense to add use_synthetic and use_ffcv integration?

**Comment by ravi-mosaicml** [comment]
> > use_synthetic
> 
> @ravi-mosaicml
> 
> The way SyntheticBatchPairDataset is created won't work with FFCV in the spirit of synthetic. FFCC will create a full dataset (i.e., no difference in its size and data it needs to write and then load) with the current SyntheticBatchPairDataset defaults. One way to mitigate this is to use smaller length synthetic dataset. Does it still make sense to add use_synthetic and use_ffcv integration?

Ah, I see. Agreed that a shorter dataset length would make sense in this case. I think it would be helpful to support both for performance measurements.

**Comment by ravi-mosaicml** [comment]
Finished; will track synthetic FFCV separately.
