### ISSUE TITLE
Factorization during training

### ISSUE THREAD

**Issue by dblalock** [mosaicml/composer#741]
## New Method
Right now factorization is only supported at `Event.INIT`, when the parameters are randomly initialized. We should also support factorizing any module at any time during training for greater flexibility and efficacy.

## Motivation

Most papers on factorization apply it partway through training, so our current implementation can't even replicate these approaches. There's also a lot of literature suggesting that pruning (which is similar to factorization) partway through training is more effective than pruning at the start.

With support for factorization at runtime, Composer would enable both better factorization and exploration of new factorization methods.

## [Optional] Implementation

The reason we don't support this right now is that DDP and DeepSpeed don't allow changing the set of parameters dynamically. There are two ways to work around this:

1. Stop training, factorize, and resume training
2. Have the [FactorizedModule](https://github.com/mosaicml/composer/blob/a6d3bcaf8aeea4b31d93e15597b3378899766069/composer/algorithms/factorize/factorize_modules.py#L106) subclasses keep the same Parameter tensor object, but slice it dynamically so that it's treated as being two tensors of the appropriate size. 

Option (1) would set us up to get techniques like pruning and quantization during training working, and is less janky. But option (2) _might_ be easier to implement.

It would be great to add this support to Composer, but even having a working example built on top of composer would still be valuable.

**Comment by Laserbear** [comment]
I can take a crack at this. I am leaning towards Option 1, but happy to discuss more in depth.
