### ISSUE TITLE
BlurPool enhancements

### ISSUE THREAD

**Issue by dblalock** [mosaicml/composer#743]
## New Method

[BlurPool](https://docs.mosaicml.com/en/latest/method_cards/blurpool.html) has proven to be one of the most reliable speedup methods for vision tasks. There are a few possible enhancements, based in part on conversation with the author:

- [ ] Support Conv1d and Conv3d, not just Conv2d
- [ ] Convolve the anti-aliasing filter with the weights, not the activations. This results in a 5x5 conv instead of a 3x3, but a single op instead of two ops. This should be vastly less expensive in most cases. Ideally we intelligently choose between implementations at runtime based on profiling.
- [ ] For even-sized feature maps, try using a 4x4 filter instead of a 3x3 one. The latter biases the downsampling to place more weight on odd-numbered spatial positions.
- [ ] For strided convs, have an option to downsample during the blur, and do a non-strided conv. For a 2x2 strided conv, this reduces the activation memory bandwidth by a factor of 4 for the conv. This is incompatible with the second enhancement above, but should be extremely easy to implement.

(Note that each of these should have its own PR, and ideally tracking issue if/when someone starts working on it).

## Motivation

These enhancements would make blurpool applicable to more problems and would likely result in even larger accuracy gains, as well as slightly faster runtime (maybe 5% overall, depending on architecture).

**Comment by b-thebest** [comment]
Can I work on this ?

**Comment by dblalock** [comment]
@b-thebest: Definitely, go for it!

**Comment by mvpatel2000** [comment]
Closing. Tracking elsewhere as low pri. We're open to community PRs
