### ISSUE TITLE
Relax equal shard sizes for webdatasets

### ISSUE THREAD

**Issue by abhi-mosaic** [mosaicml/composer#744]
Some datasets are so small that losing samples due to sharding constraints: `n_samples % n_shards == 0` is not acceptable. Instead, let's allow different shards to have different lengths, and loop over shards that are smaller than others.

Note that this means that some samples will be "lucky", if they are in smaller shards, and will be sampled slightly-more-often per epoch than other samples. In practice though, all shard sizes should be within 1 sample of eachother, so the effect should be small.

Re. how this would be implemented in Composer, I think we need to edit the `_size_webdataset` function, but other than that we should be good to go. We will also want to re-upload our exisiting webdatasets with the extra samples, and run some convergence tests to make sure that it all works.

**Comment by ravi-mosaicml** [comment]
Closing as we removed webdatasets
