### ISSUE TITLE
Relax `num_shards % num_workers == 0` requirement for webdatasets

### ISSUE THREAD

**Issue by abhi-mosaic** [mosaicml/composer#746]
Some datasets are so small that they cannot be efficiently sharded into a large # of `num_shards`. Though this is partially mitigated by repeating samples (see #744), it may still be unreasonable to create 64 or 128+ shards for a small validation set of only ~100 samples.

Instead, we should be able to have a small number of shards, and allow different workers to duplicately stream the shards, but subsample internally (so worker0 downloads shard0 but only processes examples 0, 2, 4... and worker1 downloads shard0 but only processes examples 1, 3, 5...). 

This would allow a small validation set to be 8 shards but still read by 64 workers (and so the dataset will be duplicately downloaded by a factor of 8x). 

To do this, we will need to edit the split functions in the webdataset init: `wds.ShardList(urls, splitter=wds.split_by_worker, nodesplitter=wds.split_by_node,...)`, so different workers can pull the same shards. We will also have to be careful to make sure that only a single worker is writing the shardcache for each duplicated shard. Finally, we probably want to enforce that `num_workers % num_shards == 0` is still true, otherwise the subsampling will not be evenly distributed.

Overall, this will require some changes to both webdataset and Composer, and should probably wait until after #744 is complete.

**Comment by ravi-mosaicml** [comment]
Closing as we removed webdatasets
