### ISSUE TITLE
Provide a command to run a CI test locally in logs

### ISSUE THREAD

**Issue by dskhudia** [mosaicml/composer#757]
## 🚀 Feature Request
It would be nice to provide the command used to run a CI test in the logs. 

## Motivation
When a CI test fails on  PR, sometime it's just easy to fix just by looking at the CI logs and at other times it is not. Therefore,  a way to reproduce it locally makes it much more easier to debug.

**Comment by ravi-mosaicml** [comment]
CONTRIBUTING.md has instructions on how to run tests locally. Are you able to produce the issue locally by running the commands listed in that document?

**Comment by dskhudia** [comment]
I do see the commands there but that's not an obvious place to look. Something like the following at the top in logs would be  much more easier to find. 

```
******** To Reproduce locally, run the following command *******
<command>
```
