### ISSUE TITLE
Algorithm Composability API

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#76]
When running tests, we validate that algorithms run on each model type. Some algorithms are not compatible with some models (e.g. NLP algs on image classification models), so we manually hard-code this in the tests. It would be helpful to have a first-class API to get which models support which algorithms, and which algorithms support which models.

The engine could also use this information to perform a static analysis to detect runtime issues before they arise.

One possible design could be to have a `ModelType` that would work like this:

```python3

class ModelType(StringEnum):
    CLASSIFICATION = "Classification"
    NLP = "Nlp"
    ...

class BaseMosaicModel:
    model_type: ModelType   # would be set on each model
    ...

class Algorithm:
    @classmethod
    def get_supported_model_types(cls):
        return list(ModelType)    # can be overridden on each algorithm
```

**Comment by mvpatel2000** [comment]
We sort of do this with engine compilation passes. Closing for now since we won't be building a full n^2 compatibility graph
