### ISSUE TITLE
Auto-TCP Port Selection by default

### ISSUE THREAD

**Issue by Averylamp** [mosaicml/composer#77]
1.  Run `.fit()` twice on the same Trainer in a script or notebook (not cleaned up port usage for `torch.distributed`)

## Expected behavior

Ideally the Trainer by default won't use a static port in `TCPStore` and instead select an open port to use for `torch.distributed` coordination.

**Comment by ravi-mosaicml** [comment]
#65 uses a hash store when training without using the launch script, so this issue should be resolved in Jupyter

For the launch script, it is possible to auto-select ports; however, there will be a race condition between when the launch script auto-selects a free port and when the training script calls `torch.distributed.initialize_process_group`. However, we will add this in with a warning.
