### ISSUE TITLE
Make algorithm hparams schedulable

### ISSUE THREAD

**Issue by growlix** [mosaicml/composer#780]
## 🚀 Feature Request
It would be very useful for researchers (inside and outside of Mosaic) if algorithm hparams were schedulable. There are also potential gains to be achieved by scheduling regularization (sometimes referred to as the [Slingshot Effect](https://arxiv.org/abs/2002.08973)).

## Implementation
I think the most straightforward approach would be to extend our LR schedulers (and corresponding config syntax) to algorithm hparams.

**Comment by mvpatel2000** [comment]
YAHP is gone
