### ISSUE TITLE
Add test cases for FFCV

### ISSUE THREAD

**Issue by ravi-mosaicml** [mosaicml/composer#803]
1. For the FFCV dataset hparams, it would be nice if the `use_ffcv` option was compatible with `use_synthetic`. If both flags are set, then we should return a synthetic FFCV dataset,
2. Let's parameterize the existing dataset tests to run with both ffcv enabled and disabled.
3. Let's parameterize the existing training tests to test training with both ffcv enabled and disabled.

**Comment by hanlint** [comment]
Closing -- merging into 737
