### ISSUE TITLE
Update conditional imports to use MissingConditionalImportError

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#814]
Any conditional import (seen in `wandb_logger.py`, `brats.py`, `timm/model.py`, `ssd.py`, etc), should now use the [MissingConditionalImportErrors](https://github.com/mosaicml/composer/blob/dev/composer/utils/import_helpers.py#L12) class.

**Comment by IanWorley** [comment]
I will take a shot at this issue

**Comment by hanlint** [comment]
Great, thank you!

**Comment by moinnadeem** [comment]
Great, let me know if you have any questions @IanWorley!

Here's some more details:
1. Look for any file that contains the text "if using pip" -- this is informing the user that they might need to install extra packages. If you need a hand finding these files, then let us know! I see the following: 
`composer/datasets/brats.py, `composer/loggers/wandb_logger.py`, `composer/models/unet/unet.py`, `composer/trainer/trainer.py`, `composer/models/ssd/ssd.py`, `composer/models/vit_small_patch16/hparams.py`, `composer/models/timm/model.py`, and `composer/models/timm/timm_hparams.py`. 

2. Replace the ImportError with a [MissingConditionalImportError](https://github.com/mosaicml/composer/blob/dev/composer/utils/import_helpers.py#L12).

Happy to quickly review the PR whenever you have it ready!

**Comment by ravi-mosaicml** [comment]
Closed via #835
