### ISSUE TITLE
Refactor Models

### ISSUE THREAD

**Issue by A-Jacobson** [mosaicml/composer#834]
The models module could use some general cleanup:

- Move ComposerClassifier out of base.py as it's not a base class.
- Move ComposerTransformer into base.py as it is a base class (pending work into general transformer factory)
- Unify naming scheme for models - some models are Composer<Architecture> some Architecture
- Move metrics out of losses.py and nlp_metrics.py into a separate metrics module.
- Maybe remove soft_cross_entropy as default pytorch CEloss supports dense labels now (depending on our supported pt versions)

steps: 

- [x] https://github.com/mosaicml/composer/pull/788
- [x] https://github.com/mosaicml/composer/pull/790
- [x] https://github.com/mosaicml/composer/pull/791
- [ ] part4 - split hf nlp models into tasks

**Comment by ravi-mosaicml** [comment]
Closing as we have other issues to track HF integration and the benchmarks refactor
