### ISSUE TITLE
Add "Best" to WandB logger

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#841]
Instead of logging the summary metrics at the very end with WandB, I would be interested in logging the best (ie. max or min) metrics during training.

**Comment by abhi-mosaic** [comment]
Relevant WandB API: https://docs.wandb.ai/guides/track/log#customize-the-summary

Looked into this a while back, we could add some hooks for something like `wandb.define_metric("loss", summary="best")`. This may or may not be reflected well in the WandB UI, haven't tried it yet.

**Comment by ravi-mosaicml** [comment]
For this, would these alternatives work?

* Use a custom entrypoint that manually calls `wandb.define_metric` after constructing the `trainer` but before `Trainer.fit` is called
* Add a custom callback that manually configures wandb.define_metric` on Event.INIT
* Create a custom metric that tracks what should be plotted, and log that directly.

I'm hesitant to add in additional parameters into Composer's `WandBLogger` and couple it too tightly to the wandb api, as then we will be responsible for updating it as the WandB API changes. Feel free to re-open the issue if none of these suggestions would work.
