### ISSUE TITLE
Multi node training - Trainer freezes

### ISSUE THREAD

**Issue by shrinath-suresh** [mosaicml/composer#855]
** Environment **
AWS p3.8xlarge - Two nodes (Each 4 GPUs)

- OS: [Ubuntu 18.04]
- Hardware (GPU, or instance type): [V100]

AWS Deep Learning AMI (Ubuntu 18.04)

Cuda version - 10.2

** To reproduce

Created python script from [composer example notebook](https://colab.research.google.com/github/mosaicml/composer/blob/dev/notebooks/up_and_running_with_composer.ipynb)

```
import time

import torch

import composer
from torchvision import datasets, transforms
#from composer import models
from composer.models import ComposerResNetCIFAR

torch.manual_seed(42) # For replicability


from composer.utils import dist
print("World Size:", dist.get_world_size())
print("Local rank:", dist.get_local_rank())
print("Global rank:", dist.get_global_rank())


data_directory = "../data"

# Normalization constants
mean = (0.507, 0.487, 0.441)
std = (0.267, 0.256, 0.276)

batch_size = 1024

cifar10_transforms = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean, std)])

train_dataset = datasets.CIFAR10(data_directory, train=True, download=True, transform=cifar10_transforms)
test_dataset = datasets.CIFAR10(data_directory, train=False, download=True, transform=cifar10_transforms)

train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_dataloader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=True)



model = ComposerResNetCIFAR(model_name='resnet_56', num_classes=10)

#model = models.CIFAR10_ResNet56()



optimizer = composer.optim.DecoupledSGDW(
    model.parameters(), # Model parameters to update
    lr=0.05, # Peak learning rate
    momentum=0.9,
    weight_decay=2.0e-3 # If this looks large, it's because its not scaled by the LR as in non-decoupled weight decay
    )


lr_scheduler = composer.optim.LinearWithWarmupScheduler(
    t_warmup="1ep", # Warm up over 1 epoch
    alpha_i=1.0, # Flat LR schedule achieved by having alpha_i == alpha_f
    alpha_f=1.0
)


train_epochs = "3ep" # Train for 3 epochs because we're assuming Colab environment and hardware
device = "gpu" # Train on the GPU

print("Initializing trainer")
trainer = composer.trainer.Trainer(
    model=model,
    train_dataloader=train_dataloader,
    eval_dataloader=test_dataloader,
    max_duration=train_epochs,
    optimizers=optimizer,
    schedulers=lr_scheduler,
    device=device
)


start_time = time.perf_counter()
trainer.fit()
end_time = time.perf_counter()
print(f"It took {end_time - start_time:0.4f} seconds to train")

```

To ensure the script is working run the following command in any of the node

```
composer -n 4 cifar.py
```
The single node training runs sucessfully.

Select one node as master and run the following command in both the nodes simultaneously 

```
composer --world_size 8 -n 4 --master_addr 172.31.29.180 --master_port 12345 cifar.py
```

## Expected behavior

Training should run successfully.

However, the run freezes while initialising Trainer

```
World Size: 8
Local rank: 0
Global rank: 0
Files already downloaded and verified
Files already downloaded and verified
Initializing trainer
```

**Comment by jbloxham** [comment]
Hi @shrinath-suresh , I'm glad to hear you're using Composer for multi-node training! I think the fix may be that you need to specify the `--base_rank` parameter to the `composer` CLI tool. In this case, your master node (i.e. the one with IP = `master_addr`) should specify `--base_rank 0`, and your second node should specify `--base_rank 4`. Can you see if that works? I'll also take a look to see if we can make our documentation for multi-node training any clearer, or better yet, see if we can remove the need for this `--base_rank` param.

**Comment by ravi-mosaicml** [comment]
Glad it worked with the base rank parameter. Though it should be possible, we do not have any documentation on using Composer with a slurm cluster.

**Comment by shrinath-suresh** [comment]
Thanks @ravi-mosaicml @jbloxham

**Comment by awsankur** [comment]
An example implementation with Slurm 
https://github.com/aws-samples/awsome-distributed-training/blob/main/3.test_cases/6.stable-diffusion/multi-node/2.train.sbatch
