### ISSUE TITLE
Time initialization behaves inconsistently

### ISSUE THREAD

**Issue by coryMosaicML** [mosaicml/composer#907]
## To reproduce

Creating an instance of time this way fails correctly because noninteger values are not allowed when the unit is epochs:
```
from composer.core import Time, TimeUnit

time = Time(0.5, TimeUnit.EPOCH)
```

However, creating it this way succeeds, but not with the value the user intended:
```
from composer.core import Time, TimeUnit

time = Time.from_timestring("0.5ep")
print(time)
```
```Time(0, TimeUnit.EPOCH)```

## Expected behavior

Both of these should fail because integer values are required when using epoch units. The same behavior also exists for units of batches, samples, and tokens. Right now, converting from float to integer using `from_timestring` can potentially introduce unexpected and difficult to find bugs.

## Additional information
A better solution could be to allow non-integer values for these units. A time of `0.5 epochs` is a valid time, and would be useful in cases where a quantity has units of time but should not be restricted to integer values.

**Comment by ravi-mosaicml** [comment]
The time tracking design does not incorporate any time conversion between units, so supporting fractional epochs will not be possible. But yes, we should error if `int(time) != float(time)` when the unit is epochs / batches / tokens / samples.
