### ISSUE TITLE
Refactor logging of `rank_zero_seed`

### ISSUE THREAD

**Issue by abhi-mosaic** [mosaicml/composer#931]
This line is logging the `rank_zero_seed` as if it is  time series data, but it's a static value that is only configured once. It looks very out of place in logger backends like WandB. I think `rank_zero_seed` should be stored in config somewhere but not logged as time series.

This can be done by either promoting it to the `TrainerHparams`, or creating a new `update_config()` function that `LoggerDestinations` have to implement.

Also a UX bug -- if each rank is logging in distributed training, then the `seed` stored in each rank's config is now incorrect because `Trainer` has overridden it to be `rank_zero_seed + rank`. Are there any other codepaths we are overriding values in the config?

https://github.com/mosaicml/composer/blob/204129b810ce71d4089781b6ee2bef9f0b2703f1/composer/trainer/trainer.py#L873

**Comment by abhi-mosaic** [comment]
This is what WandB looks like right now:
<img width="1232" alt="Screen Shot 2022-04-20 at 1 44 58 PM" src="https://user-images.githubusercontent.com/77638579/164319742-e7811197-7e35-407c-b2eb-42c25426e42c.png">

**Comment by ravi-mosaicml** [comment]
I like the idea of implementing `update_config` in the logger destinations, as different loggers may want to store config differently.

**Comment by eracah** [comment]
Closed by PR #1416

**Comment by eracah** [comment]
Closed by PR #1416
