### ISSUE TITLE
Errors are not printed to stdout when using multi-gpu training

### ISSUE THREAD

**Issue by Landanjs** [mosaicml/composer#95]
Anytime an error occurs while I am using multi-gpu training, the job crashes, but the error is not printed. I need to run the experiment with a single GPU to find what the error was.

Is there a way to fix this? It makes determining issue very difficult. 

I can try to create an example with the current release if needed.

**Comment by hanlint** [comment]
A reproducible example would be great here, thanks!

**Comment by ravi-mosaicml** [comment]
stdout and stderr for rank 1+ should be output to the `runs/` directory. Is it showing up there?

**Comment by Landanjs** [comment]
After some merges into dev, I have not encountered this issue in a while.
